package cm.cn.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Gpsinfo20171128Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    public Gpsinfo20171128Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGpsidIsNull() {
            addCriterion("gpsId is null");
            return (Criteria) this;
        }

        public Criteria andGpsidIsNotNull() {
            addCriterion("gpsId is not null");
            return (Criteria) this;
        }

        public Criteria andGpsidEqualTo(Integer value) {
            addCriterion("gpsId =", value, "gpsid");
            return (Criteria) this;
        }

        public Criteria andGpsidNotEqualTo(Integer value) {
            addCriterion("gpsId <>", value, "gpsid");
            return (Criteria) this;
        }

        public Criteria andGpsidGreaterThan(Integer value) {
            addCriterion("gpsId >", value, "gpsid");
            return (Criteria) this;
        }

        public Criteria andGpsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("gpsId >=", value, "gpsid");
            return (Criteria) this;
        }

        public Criteria andGpsidLessThan(Integer value) {
            addCriterion("gpsId <", value, "gpsid");
            return (Criteria) this;
        }

        public Criteria andGpsidLessThanOrEqualTo(Integer value) {
            addCriterion("gpsId <=", value, "gpsid");
            return (Criteria) this;
        }

        public Criteria andGpsidIn(List<Integer> values) {
            addCriterion("gpsId in", values, "gpsid");
            return (Criteria) this;
        }

        public Criteria andGpsidNotIn(List<Integer> values) {
            addCriterion("gpsId not in", values, "gpsid");
            return (Criteria) this;
        }

        public Criteria andGpsidBetween(Integer value1, Integer value2) {
            addCriterion("gpsId between", value1, value2, "gpsid");
            return (Criteria) this;
        }

        public Criteria andGpsidNotBetween(Integer value1, Integer value2) {
            addCriterion("gpsId not between", value1, value2, "gpsid");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("owner is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("owner is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(String value) {
            addCriterion("owner =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(String value) {
            addCriterion("owner <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(String value) {
            addCriterion("owner >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("owner >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(String value) {
            addCriterion("owner <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(String value) {
            addCriterion("owner <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLike(String value) {
            addCriterion("owner like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotLike(String value) {
            addCriterion("owner not like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<String> values) {
            addCriterion("owner in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<String> values) {
            addCriterion("owner not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(String value1, String value2) {
            addCriterion("owner between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(String value1, String value2) {
            addCriterion("owner not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andTenantidIsNull() {
            addCriterion("tenantId is null");
            return (Criteria) this;
        }

        public Criteria andTenantidIsNotNull() {
            addCriterion("tenantId is not null");
            return (Criteria) this;
        }

        public Criteria andTenantidEqualTo(Integer value) {
            addCriterion("tenantId =", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidNotEqualTo(Integer value) {
            addCriterion("tenantId <>", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidGreaterThan(Integer value) {
            addCriterion("tenantId >", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidGreaterThanOrEqualTo(Integer value) {
            addCriterion("tenantId >=", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidLessThan(Integer value) {
            addCriterion("tenantId <", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidLessThanOrEqualTo(Integer value) {
            addCriterion("tenantId <=", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidIn(List<Integer> values) {
            addCriterion("tenantId in", values, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidNotIn(List<Integer> values) {
            addCriterion("tenantId not in", values, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidBetween(Integer value1, Integer value2) {
            addCriterion("tenantId between", value1, value2, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidNotBetween(Integer value1, Integer value2) {
            addCriterion("tenantId not between", value1, value2, "tenantid");
            return (Criteria) this;
        }

        public Criteria andAlarmstateIsNull() {
            addCriterion("alarmState is null");
            return (Criteria) this;
        }

        public Criteria andAlarmstateIsNotNull() {
            addCriterion("alarmState is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmstateEqualTo(Integer value) {
            addCriterion("alarmState =", value, "alarmstate");
            return (Criteria) this;
        }

        public Criteria andAlarmstateNotEqualTo(Integer value) {
            addCriterion("alarmState <>", value, "alarmstate");
            return (Criteria) this;
        }

        public Criteria andAlarmstateGreaterThan(Integer value) {
            addCriterion("alarmState >", value, "alarmstate");
            return (Criteria) this;
        }

        public Criteria andAlarmstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("alarmState >=", value, "alarmstate");
            return (Criteria) this;
        }

        public Criteria andAlarmstateLessThan(Integer value) {
            addCriterion("alarmState <", value, "alarmstate");
            return (Criteria) this;
        }

        public Criteria andAlarmstateLessThanOrEqualTo(Integer value) {
            addCriterion("alarmState <=", value, "alarmstate");
            return (Criteria) this;
        }

        public Criteria andAlarmstateIn(List<Integer> values) {
            addCriterion("alarmState in", values, "alarmstate");
            return (Criteria) this;
        }

        public Criteria andAlarmstateNotIn(List<Integer> values) {
            addCriterion("alarmState not in", values, "alarmstate");
            return (Criteria) this;
        }

        public Criteria andAlarmstateBetween(Integer value1, Integer value2) {
            addCriterion("alarmState between", value1, value2, "alarmstate");
            return (Criteria) this;
        }

        public Criteria andAlarmstateNotBetween(Integer value1, Integer value2) {
            addCriterion("alarmState not between", value1, value2, "alarmstate");
            return (Criteria) this;
        }

        public Criteria andAltitudeIsNull() {
            addCriterion("altitude is null");
            return (Criteria) this;
        }

        public Criteria andAltitudeIsNotNull() {
            addCriterion("altitude is not null");
            return (Criteria) this;
        }

        public Criteria andAltitudeEqualTo(Double value) {
            addCriterion("altitude =", value, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeNotEqualTo(Double value) {
            addCriterion("altitude <>", value, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeGreaterThan(Double value) {
            addCriterion("altitude >", value, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("altitude >=", value, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeLessThan(Double value) {
            addCriterion("altitude <", value, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeLessThanOrEqualTo(Double value) {
            addCriterion("altitude <=", value, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeIn(List<Double> values) {
            addCriterion("altitude in", values, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeNotIn(List<Double> values) {
            addCriterion("altitude not in", values, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeBetween(Double value1, Double value2) {
            addCriterion("altitude between", value1, value2, "altitude");
            return (Criteria) this;
        }

        public Criteria andAltitudeNotBetween(Double value1, Double value2) {
            addCriterion("altitude not between", value1, value2, "altitude");
            return (Criteria) this;
        }

        public Criteria andCommandidIsNull() {
            addCriterion("commandId is null");
            return (Criteria) this;
        }

        public Criteria andCommandidIsNotNull() {
            addCriterion("commandId is not null");
            return (Criteria) this;
        }

        public Criteria andCommandidEqualTo(Integer value) {
            addCriterion("commandId =", value, "commandid");
            return (Criteria) this;
        }

        public Criteria andCommandidNotEqualTo(Integer value) {
            addCriterion("commandId <>", value, "commandid");
            return (Criteria) this;
        }

        public Criteria andCommandidGreaterThan(Integer value) {
            addCriterion("commandId >", value, "commandid");
            return (Criteria) this;
        }

        public Criteria andCommandidGreaterThanOrEqualTo(Integer value) {
            addCriterion("commandId >=", value, "commandid");
            return (Criteria) this;
        }

        public Criteria andCommandidLessThan(Integer value) {
            addCriterion("commandId <", value, "commandid");
            return (Criteria) this;
        }

        public Criteria andCommandidLessThanOrEqualTo(Integer value) {
            addCriterion("commandId <=", value, "commandid");
            return (Criteria) this;
        }

        public Criteria andCommandidIn(List<Integer> values) {
            addCriterion("commandId in", values, "commandid");
            return (Criteria) this;
        }

        public Criteria andCommandidNotIn(List<Integer> values) {
            addCriterion("commandId not in", values, "commandid");
            return (Criteria) this;
        }

        public Criteria andCommandidBetween(Integer value1, Integer value2) {
            addCriterion("commandId between", value1, value2, "commandid");
            return (Criteria) this;
        }

        public Criteria andCommandidNotBetween(Integer value1, Integer value2) {
            addCriterion("commandId not between", value1, value2, "commandid");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNull() {
            addCriterion("direction is null");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNotNull() {
            addCriterion("direction is not null");
            return (Criteria) this;
        }

        public Criteria andDirectionEqualTo(Integer value) {
            addCriterion("direction =", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotEqualTo(Integer value) {
            addCriterion("direction <>", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThan(Integer value) {
            addCriterion("direction >", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThanOrEqualTo(Integer value) {
            addCriterion("direction >=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThan(Integer value) {
            addCriterion("direction <", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThanOrEqualTo(Integer value) {
            addCriterion("direction <=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionIn(List<Integer> values) {
            addCriterion("direction in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotIn(List<Integer> values) {
            addCriterion("direction not in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionBetween(Integer value1, Integer value2) {
            addCriterion("direction between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotBetween(Integer value1, Integer value2) {
            addCriterion("direction not between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andGasIsNull() {
            addCriterion("gas is null");
            return (Criteria) this;
        }

        public Criteria andGasIsNotNull() {
            addCriterion("gas is not null");
            return (Criteria) this;
        }

        public Criteria andGasEqualTo(Double value) {
            addCriterion("gas =", value, "gas");
            return (Criteria) this;
        }

        public Criteria andGasNotEqualTo(Double value) {
            addCriterion("gas <>", value, "gas");
            return (Criteria) this;
        }

        public Criteria andGasGreaterThan(Double value) {
            addCriterion("gas >", value, "gas");
            return (Criteria) this;
        }

        public Criteria andGasGreaterThanOrEqualTo(Double value) {
            addCriterion("gas >=", value, "gas");
            return (Criteria) this;
        }

        public Criteria andGasLessThan(Double value) {
            addCriterion("gas <", value, "gas");
            return (Criteria) this;
        }

        public Criteria andGasLessThanOrEqualTo(Double value) {
            addCriterion("gas <=", value, "gas");
            return (Criteria) this;
        }

        public Criteria andGasIn(List<Double> values) {
            addCriterion("gas in", values, "gas");
            return (Criteria) this;
        }

        public Criteria andGasNotIn(List<Double> values) {
            addCriterion("gas not in", values, "gas");
            return (Criteria) this;
        }

        public Criteria andGasBetween(Double value1, Double value2) {
            addCriterion("gas between", value1, value2, "gas");
            return (Criteria) this;
        }

        public Criteria andGasNotBetween(Double value1, Double value2) {
            addCriterion("gas not between", value1, value2, "gas");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(Double value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(Double value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(Double value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(Double value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<Double> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<Double> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(Double value1, Double value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(Double value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(Double value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(Double value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(Double value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(Double value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<Double> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<Double> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(Double value1, Double value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(Double value1, Double value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andMileageIsNull() {
            addCriterion("mileage is null");
            return (Criteria) this;
        }

        public Criteria andMileageIsNotNull() {
            addCriterion("mileage is not null");
            return (Criteria) this;
        }

        public Criteria andMileageEqualTo(Double value) {
            addCriterion("mileage =", value, "mileage");
            return (Criteria) this;
        }

        public Criteria andMileageNotEqualTo(Double value) {
            addCriterion("mileage <>", value, "mileage");
            return (Criteria) this;
        }

        public Criteria andMileageGreaterThan(Double value) {
            addCriterion("mileage >", value, "mileage");
            return (Criteria) this;
        }

        public Criteria andMileageGreaterThanOrEqualTo(Double value) {
            addCriterion("mileage >=", value, "mileage");
            return (Criteria) this;
        }

        public Criteria andMileageLessThan(Double value) {
            addCriterion("mileage <", value, "mileage");
            return (Criteria) this;
        }

        public Criteria andMileageLessThanOrEqualTo(Double value) {
            addCriterion("mileage <=", value, "mileage");
            return (Criteria) this;
        }

        public Criteria andMileageIn(List<Double> values) {
            addCriterion("mileage in", values, "mileage");
            return (Criteria) this;
        }

        public Criteria andMileageNotIn(List<Double> values) {
            addCriterion("mileage not in", values, "mileage");
            return (Criteria) this;
        }

        public Criteria andMileageBetween(Double value1, Double value2) {
            addCriterion("mileage between", value1, value2, "mileage");
            return (Criteria) this;
        }

        public Criteria andMileageNotBetween(Double value1, Double value2) {
            addCriterion("mileage not between", value1, value2, "mileage");
            return (Criteria) this;
        }

        public Criteria andPlatenoIsNull() {
            addCriterion("plateNo is null");
            return (Criteria) this;
        }

        public Criteria andPlatenoIsNotNull() {
            addCriterion("plateNo is not null");
            return (Criteria) this;
        }

        public Criteria andPlatenoEqualTo(String value) {
            addCriterion("plateNo =", value, "plateno");
            return (Criteria) this;
        }

        public Criteria andPlatenoNotEqualTo(String value) {
            addCriterion("plateNo <>", value, "plateno");
            return (Criteria) this;
        }

        public Criteria andPlatenoGreaterThan(String value) {
            addCriterion("plateNo >", value, "plateno");
            return (Criteria) this;
        }

        public Criteria andPlatenoGreaterThanOrEqualTo(String value) {
            addCriterion("plateNo >=", value, "plateno");
            return (Criteria) this;
        }

        public Criteria andPlatenoLessThan(String value) {
            addCriterion("plateNo <", value, "plateno");
            return (Criteria) this;
        }

        public Criteria andPlatenoLessThanOrEqualTo(String value) {
            addCriterion("plateNo <=", value, "plateno");
            return (Criteria) this;
        }

        public Criteria andPlatenoLike(String value) {
            addCriterion("plateNo like", value, "plateno");
            return (Criteria) this;
        }

        public Criteria andPlatenoNotLike(String value) {
            addCriterion("plateNo not like", value, "plateno");
            return (Criteria) this;
        }

        public Criteria andPlatenoIn(List<String> values) {
            addCriterion("plateNo in", values, "plateno");
            return (Criteria) this;
        }

        public Criteria andPlatenoNotIn(List<String> values) {
            addCriterion("plateNo not in", values, "plateno");
            return (Criteria) this;
        }

        public Criteria andPlatenoBetween(String value1, String value2) {
            addCriterion("plateNo between", value1, value2, "plateno");
            return (Criteria) this;
        }

        public Criteria andPlatenoNotBetween(String value1, String value2) {
            addCriterion("plateNo not between", value1, value2, "plateno");
            return (Criteria) this;
        }

        public Criteria andRecordvelocityIsNull() {
            addCriterion("recordVelocity is null");
            return (Criteria) this;
        }

        public Criteria andRecordvelocityIsNotNull() {
            addCriterion("recordVelocity is not null");
            return (Criteria) this;
        }

        public Criteria andRecordvelocityEqualTo(Double value) {
            addCriterion("recordVelocity =", value, "recordvelocity");
            return (Criteria) this;
        }

        public Criteria andRecordvelocityNotEqualTo(Double value) {
            addCriterion("recordVelocity <>", value, "recordvelocity");
            return (Criteria) this;
        }

        public Criteria andRecordvelocityGreaterThan(Double value) {
            addCriterion("recordVelocity >", value, "recordvelocity");
            return (Criteria) this;
        }

        public Criteria andRecordvelocityGreaterThanOrEqualTo(Double value) {
            addCriterion("recordVelocity >=", value, "recordvelocity");
            return (Criteria) this;
        }

        public Criteria andRecordvelocityLessThan(Double value) {
            addCriterion("recordVelocity <", value, "recordvelocity");
            return (Criteria) this;
        }

        public Criteria andRecordvelocityLessThanOrEqualTo(Double value) {
            addCriterion("recordVelocity <=", value, "recordvelocity");
            return (Criteria) this;
        }

        public Criteria andRecordvelocityIn(List<Double> values) {
            addCriterion("recordVelocity in", values, "recordvelocity");
            return (Criteria) this;
        }

        public Criteria andRecordvelocityNotIn(List<Double> values) {
            addCriterion("recordVelocity not in", values, "recordvelocity");
            return (Criteria) this;
        }

        public Criteria andRecordvelocityBetween(Double value1, Double value2) {
            addCriterion("recordVelocity between", value1, value2, "recordvelocity");
            return (Criteria) this;
        }

        public Criteria andRecordvelocityNotBetween(Double value1, Double value2) {
            addCriterion("recordVelocity not between", value1, value2, "recordvelocity");
            return (Criteria) this;
        }

        public Criteria andRunstatusIsNull() {
            addCriterion("runStatus is null");
            return (Criteria) this;
        }

        public Criteria andRunstatusIsNotNull() {
            addCriterion("runStatus is not null");
            return (Criteria) this;
        }

        public Criteria andRunstatusEqualTo(String value) {
            addCriterion("runStatus =", value, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusNotEqualTo(String value) {
            addCriterion("runStatus <>", value, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusGreaterThan(String value) {
            addCriterion("runStatus >", value, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusGreaterThanOrEqualTo(String value) {
            addCriterion("runStatus >=", value, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusLessThan(String value) {
            addCriterion("runStatus <", value, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusLessThanOrEqualTo(String value) {
            addCriterion("runStatus <=", value, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusLike(String value) {
            addCriterion("runStatus like", value, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusNotLike(String value) {
            addCriterion("runStatus not like", value, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusIn(List<String> values) {
            addCriterion("runStatus in", values, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusNotIn(List<String> values) {
            addCriterion("runStatus not in", values, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusBetween(String value1, String value2) {
            addCriterion("runStatus between", value1, value2, "runstatus");
            return (Criteria) this;
        }

        public Criteria andRunstatusNotBetween(String value1, String value2) {
            addCriterion("runStatus not between", value1, value2, "runstatus");
            return (Criteria) this;
        }

        public Criteria andSendtimeIsNull() {
            addCriterion("sendTime is null");
            return (Criteria) this;
        }

        public Criteria andSendtimeIsNotNull() {
            addCriterion("sendTime is not null");
            return (Criteria) this;
        }

        public Criteria andSendtimeEqualTo(Date value) {
            addCriterion("sendTime =", value, "sendtime");
            return (Criteria) this;
        }

        public Criteria andSendtimeNotEqualTo(Date value) {
            addCriterion("sendTime <>", value, "sendtime");
            return (Criteria) this;
        }

        public Criteria andSendtimeGreaterThan(Date value) {
            addCriterion("sendTime >", value, "sendtime");
            return (Criteria) this;
        }

        public Criteria andSendtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sendTime >=", value, "sendtime");
            return (Criteria) this;
        }

        public Criteria andSendtimeLessThan(Date value) {
            addCriterion("sendTime <", value, "sendtime");
            return (Criteria) this;
        }

        public Criteria andSendtimeLessThanOrEqualTo(Date value) {
            addCriterion("sendTime <=", value, "sendtime");
            return (Criteria) this;
        }

        public Criteria andSendtimeIn(List<Date> values) {
            addCriterion("sendTime in", values, "sendtime");
            return (Criteria) this;
        }

        public Criteria andSendtimeNotIn(List<Date> values) {
            addCriterion("sendTime not in", values, "sendtime");
            return (Criteria) this;
        }

        public Criteria andSendtimeBetween(Date value1, Date value2) {
            addCriterion("sendTime between", value1, value2, "sendtime");
            return (Criteria) this;
        }

        public Criteria andSendtimeNotBetween(Date value1, Date value2) {
            addCriterion("sendTime not between", value1, value2, "sendtime");
            return (Criteria) this;
        }

        public Criteria andSimnoIsNull() {
            addCriterion("simNo is null");
            return (Criteria) this;
        }

        public Criteria andSimnoIsNotNull() {
            addCriterion("simNo is not null");
            return (Criteria) this;
        }

        public Criteria andSimnoEqualTo(String value) {
            addCriterion("simNo =", value, "simno");
            return (Criteria) this;
        }

        public Criteria andSimnoNotEqualTo(String value) {
            addCriterion("simNo <>", value, "simno");
            return (Criteria) this;
        }

        public Criteria andSimnoGreaterThan(String value) {
            addCriterion("simNo >", value, "simno");
            return (Criteria) this;
        }

        public Criteria andSimnoGreaterThanOrEqualTo(String value) {
            addCriterion("simNo >=", value, "simno");
            return (Criteria) this;
        }

        public Criteria andSimnoLessThan(String value) {
            addCriterion("simNo <", value, "simno");
            return (Criteria) this;
        }

        public Criteria andSimnoLessThanOrEqualTo(String value) {
            addCriterion("simNo <=", value, "simno");
            return (Criteria) this;
        }

        public Criteria andSimnoLike(String value) {
            addCriterion("simNo like", value, "simno");
            return (Criteria) this;
        }

        public Criteria andSimnoNotLike(String value) {
            addCriterion("simNo not like", value, "simno");
            return (Criteria) this;
        }

        public Criteria andSimnoIn(List<String> values) {
            addCriterion("simNo in", values, "simno");
            return (Criteria) this;
        }

        public Criteria andSimnoNotIn(List<String> values) {
            addCriterion("simNo not in", values, "simno");
            return (Criteria) this;
        }

        public Criteria andSimnoBetween(String value1, String value2) {
            addCriterion("simNo between", value1, value2, "simno");
            return (Criteria) this;
        }

        public Criteria andSimnoNotBetween(String value1, String value2) {
            addCriterion("simNo not between", value1, value2, "simno");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andValidIsNull() {
            addCriterion("valid is null");
            return (Criteria) this;
        }

        public Criteria andValidIsNotNull() {
            addCriterion("valid is not null");
            return (Criteria) this;
        }

        public Criteria andValidEqualTo(Boolean value) {
            addCriterion("valid =", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotEqualTo(Boolean value) {
            addCriterion("valid <>", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThan(Boolean value) {
            addCriterion("valid >", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("valid >=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThan(Boolean value) {
            addCriterion("valid <", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThanOrEqualTo(Boolean value) {
            addCriterion("valid <=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidIn(List<Boolean> values) {
            addCriterion("valid in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotIn(List<Boolean> values) {
            addCriterion("valid not in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidBetween(Boolean value1, Boolean value2) {
            addCriterion("valid between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("valid not between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andVelocityIsNull() {
            addCriterion("velocity is null");
            return (Criteria) this;
        }

        public Criteria andVelocityIsNotNull() {
            addCriterion("velocity is not null");
            return (Criteria) this;
        }

        public Criteria andVelocityEqualTo(Double value) {
            addCriterion("velocity =", value, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityNotEqualTo(Double value) {
            addCriterion("velocity <>", value, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityGreaterThan(Double value) {
            addCriterion("velocity >", value, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityGreaterThanOrEqualTo(Double value) {
            addCriterion("velocity >=", value, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityLessThan(Double value) {
            addCriterion("velocity <", value, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityLessThanOrEqualTo(Double value) {
            addCriterion("velocity <=", value, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityIn(List<Double> values) {
            addCriterion("velocity in", values, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityNotIn(List<Double> values) {
            addCriterion("velocity not in", values, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityBetween(Double value1, Double value2) {
            addCriterion("velocity between", value1, value2, "velocity");
            return (Criteria) this;
        }

        public Criteria andVelocityNotBetween(Double value1, Double value2) {
            addCriterion("velocity not between", value1, value2, "velocity");
            return (Criteria) this;
        }

        public Criteria andSignalVIsNull() {
            addCriterion("signal_v is null");
            return (Criteria) this;
        }

        public Criteria andSignalVIsNotNull() {
            addCriterion("signal_v is not null");
            return (Criteria) this;
        }

        public Criteria andSignalVEqualTo(Integer value) {
            addCriterion("signal_v =", value, "signalV");
            return (Criteria) this;
        }

        public Criteria andSignalVNotEqualTo(Integer value) {
            addCriterion("signal_v <>", value, "signalV");
            return (Criteria) this;
        }

        public Criteria andSignalVGreaterThan(Integer value) {
            addCriterion("signal_v >", value, "signalV");
            return (Criteria) this;
        }

        public Criteria andSignalVGreaterThanOrEqualTo(Integer value) {
            addCriterion("signal_v >=", value, "signalV");
            return (Criteria) this;
        }

        public Criteria andSignalVLessThan(Integer value) {
            addCriterion("signal_v <", value, "signalV");
            return (Criteria) this;
        }

        public Criteria andSignalVLessThanOrEqualTo(Integer value) {
            addCriterion("signal_v <=", value, "signalV");
            return (Criteria) this;
        }

        public Criteria andSignalVIn(List<Integer> values) {
            addCriterion("signal_v in", values, "signalV");
            return (Criteria) this;
        }

        public Criteria andSignalVNotIn(List<Integer> values) {
            addCriterion("signal_v not in", values, "signalV");
            return (Criteria) this;
        }

        public Criteria andSignalVBetween(Integer value1, Integer value2) {
            addCriterion("signal_v between", value1, value2, "signalV");
            return (Criteria) this;
        }

        public Criteria andSignalVNotBetween(Integer value1, Integer value2) {
            addCriterion("signal_v not between", value1, value2, "signalV");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 28 10:55:13 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gpsinfo20171128
     *
     * @mbggenerated Tue Nov 28 10:55:13 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}