package cm.cn.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class HlCarinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public HlCarinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCarNumIsNull() {
            addCriterion("car_num is null");
            return (Criteria) this;
        }

        public Criteria andCarNumIsNotNull() {
            addCriterion("car_num is not null");
            return (Criteria) this;
        }

        public Criteria andCarNumEqualTo(String value) {
            addCriterion("car_num =", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumNotEqualTo(String value) {
            addCriterion("car_num <>", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumGreaterThan(String value) {
            addCriterion("car_num >", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumGreaterThanOrEqualTo(String value) {
            addCriterion("car_num >=", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumLessThan(String value) {
            addCriterion("car_num <", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumLessThanOrEqualTo(String value) {
            addCriterion("car_num <=", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumLike(String value) {
            addCriterion("car_num like", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumNotLike(String value) {
            addCriterion("car_num not like", value, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumIn(List<String> values) {
            addCriterion("car_num in", values, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumNotIn(List<String> values) {
            addCriterion("car_num not in", values, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumBetween(String value1, String value2) {
            addCriterion("car_num between", value1, value2, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarNumNotBetween(String value1, String value2) {
            addCriterion("car_num not between", value1, value2, "carNum");
            return (Criteria) this;
        }

        public Criteria andCarnumColorIsNull() {
            addCriterion("carnum_color is null");
            return (Criteria) this;
        }

        public Criteria andCarnumColorIsNotNull() {
            addCriterion("carnum_color is not null");
            return (Criteria) this;
        }

        public Criteria andCarnumColorEqualTo(String value) {
            addCriterion("carnum_color =", value, "carnumColor");
            return (Criteria) this;
        }

        public Criteria andCarnumColorNotEqualTo(String value) {
            addCriterion("carnum_color <>", value, "carnumColor");
            return (Criteria) this;
        }

        public Criteria andCarnumColorGreaterThan(String value) {
            addCriterion("carnum_color >", value, "carnumColor");
            return (Criteria) this;
        }

        public Criteria andCarnumColorGreaterThanOrEqualTo(String value) {
            addCriterion("carnum_color >=", value, "carnumColor");
            return (Criteria) this;
        }

        public Criteria andCarnumColorLessThan(String value) {
            addCriterion("carnum_color <", value, "carnumColor");
            return (Criteria) this;
        }

        public Criteria andCarnumColorLessThanOrEqualTo(String value) {
            addCriterion("carnum_color <=", value, "carnumColor");
            return (Criteria) this;
        }

        public Criteria andCarnumColorLike(String value) {
            addCriterion("carnum_color like", value, "carnumColor");
            return (Criteria) this;
        }

        public Criteria andCarnumColorNotLike(String value) {
            addCriterion("carnum_color not like", value, "carnumColor");
            return (Criteria) this;
        }

        public Criteria andCarnumColorIn(List<String> values) {
            addCriterion("carnum_color in", values, "carnumColor");
            return (Criteria) this;
        }

        public Criteria andCarnumColorNotIn(List<String> values) {
            addCriterion("carnum_color not in", values, "carnumColor");
            return (Criteria) this;
        }

        public Criteria andCarnumColorBetween(String value1, String value2) {
            addCriterion("carnum_color between", value1, value2, "carnumColor");
            return (Criteria) this;
        }

        public Criteria andCarnumColorNotBetween(String value1, String value2) {
            addCriterion("carnum_color not between", value1, value2, "carnumColor");
            return (Criteria) this;
        }

        public Criteria andGuacarNumIsNull() {
            addCriterion("guacar_num is null");
            return (Criteria) this;
        }

        public Criteria andGuacarNumIsNotNull() {
            addCriterion("guacar_num is not null");
            return (Criteria) this;
        }

        public Criteria andGuacarNumEqualTo(String value) {
            addCriterion("guacar_num =", value, "guacarNum");
            return (Criteria) this;
        }

        public Criteria andGuacarNumNotEqualTo(String value) {
            addCriterion("guacar_num <>", value, "guacarNum");
            return (Criteria) this;
        }

        public Criteria andGuacarNumGreaterThan(String value) {
            addCriterion("guacar_num >", value, "guacarNum");
            return (Criteria) this;
        }

        public Criteria andGuacarNumGreaterThanOrEqualTo(String value) {
            addCriterion("guacar_num >=", value, "guacarNum");
            return (Criteria) this;
        }

        public Criteria andGuacarNumLessThan(String value) {
            addCriterion("guacar_num <", value, "guacarNum");
            return (Criteria) this;
        }

        public Criteria andGuacarNumLessThanOrEqualTo(String value) {
            addCriterion("guacar_num <=", value, "guacarNum");
            return (Criteria) this;
        }

        public Criteria andGuacarNumLike(String value) {
            addCriterion("guacar_num like", value, "guacarNum");
            return (Criteria) this;
        }

        public Criteria andGuacarNumNotLike(String value) {
            addCriterion("guacar_num not like", value, "guacarNum");
            return (Criteria) this;
        }

        public Criteria andGuacarNumIn(List<String> values) {
            addCriterion("guacar_num in", values, "guacarNum");
            return (Criteria) this;
        }

        public Criteria andGuacarNumNotIn(List<String> values) {
            addCriterion("guacar_num not in", values, "guacarNum");
            return (Criteria) this;
        }

        public Criteria andGuacarNumBetween(String value1, String value2) {
            addCriterion("guacar_num between", value1, value2, "guacarNum");
            return (Criteria) this;
        }

        public Criteria andGuacarNumNotBetween(String value1, String value2) {
            addCriterion("guacar_num not between", value1, value2, "guacarNum");
            return (Criteria) this;
        }

        public Criteria andCarColorIsNull() {
            addCriterion("car_color is null");
            return (Criteria) this;
        }

        public Criteria andCarColorIsNotNull() {
            addCriterion("car_color is not null");
            return (Criteria) this;
        }

        public Criteria andCarColorEqualTo(String value) {
            addCriterion("car_color =", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorNotEqualTo(String value) {
            addCriterion("car_color <>", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorGreaterThan(String value) {
            addCriterion("car_color >", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorGreaterThanOrEqualTo(String value) {
            addCriterion("car_color >=", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorLessThan(String value) {
            addCriterion("car_color <", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorLessThanOrEqualTo(String value) {
            addCriterion("car_color <=", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorLike(String value) {
            addCriterion("car_color like", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorNotLike(String value) {
            addCriterion("car_color not like", value, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorIn(List<String> values) {
            addCriterion("car_color in", values, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorNotIn(List<String> values) {
            addCriterion("car_color not in", values, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorBetween(String value1, String value2) {
            addCriterion("car_color between", value1, value2, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarColorNotBetween(String value1, String value2) {
            addCriterion("car_color not between", value1, value2, "carColor");
            return (Criteria) this;
        }

        public Criteria andCarTypeIsNull() {
            addCriterion("car_type is null");
            return (Criteria) this;
        }

        public Criteria andCarTypeIsNotNull() {
            addCriterion("car_type is not null");
            return (Criteria) this;
        }

        public Criteria andCarTypeEqualTo(String value) {
            addCriterion("car_type =", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotEqualTo(String value) {
            addCriterion("car_type <>", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeGreaterThan(String value) {
            addCriterion("car_type >", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeGreaterThanOrEqualTo(String value) {
            addCriterion("car_type >=", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeLessThan(String value) {
            addCriterion("car_type <", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeLessThanOrEqualTo(String value) {
            addCriterion("car_type <=", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeLike(String value) {
            addCriterion("car_type like", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotLike(String value) {
            addCriterion("car_type not like", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeIn(List<String> values) {
            addCriterion("car_type in", values, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotIn(List<String> values) {
            addCriterion("car_type not in", values, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeBetween(String value1, String value2) {
            addCriterion("car_type between", value1, value2, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotBetween(String value1, String value2) {
            addCriterion("car_type not between", value1, value2, "carType");
            return (Criteria) this;
        }

        public Criteria andLenIsNull() {
            addCriterion("len is null");
            return (Criteria) this;
        }

        public Criteria andLenIsNotNull() {
            addCriterion("len is not null");
            return (Criteria) this;
        }

        public Criteria andLenEqualTo(Integer value) {
            addCriterion("len =", value, "len");
            return (Criteria) this;
        }

        public Criteria andLenNotEqualTo(Integer value) {
            addCriterion("len <>", value, "len");
            return (Criteria) this;
        }

        public Criteria andLenGreaterThan(Integer value) {
            addCriterion("len >", value, "len");
            return (Criteria) this;
        }

        public Criteria andLenGreaterThanOrEqualTo(Integer value) {
            addCriterion("len >=", value, "len");
            return (Criteria) this;
        }

        public Criteria andLenLessThan(Integer value) {
            addCriterion("len <", value, "len");
            return (Criteria) this;
        }

        public Criteria andLenLessThanOrEqualTo(Integer value) {
            addCriterion("len <=", value, "len");
            return (Criteria) this;
        }

        public Criteria andLenIn(List<Integer> values) {
            addCriterion("len in", values, "len");
            return (Criteria) this;
        }

        public Criteria andLenNotIn(List<Integer> values) {
            addCriterion("len not in", values, "len");
            return (Criteria) this;
        }

        public Criteria andLenBetween(Integer value1, Integer value2) {
            addCriterion("len between", value1, value2, "len");
            return (Criteria) this;
        }

        public Criteria andLenNotBetween(Integer value1, Integer value2) {
            addCriterion("len not between", value1, value2, "len");
            return (Criteria) this;
        }

        public Criteria andWideIsNull() {
            addCriterion("wide is null");
            return (Criteria) this;
        }

        public Criteria andWideIsNotNull() {
            addCriterion("wide is not null");
            return (Criteria) this;
        }

        public Criteria andWideEqualTo(Integer value) {
            addCriterion("wide =", value, "wide");
            return (Criteria) this;
        }

        public Criteria andWideNotEqualTo(Integer value) {
            addCriterion("wide <>", value, "wide");
            return (Criteria) this;
        }

        public Criteria andWideGreaterThan(Integer value) {
            addCriterion("wide >", value, "wide");
            return (Criteria) this;
        }

        public Criteria andWideGreaterThanOrEqualTo(Integer value) {
            addCriterion("wide >=", value, "wide");
            return (Criteria) this;
        }

        public Criteria andWideLessThan(Integer value) {
            addCriterion("wide <", value, "wide");
            return (Criteria) this;
        }

        public Criteria andWideLessThanOrEqualTo(Integer value) {
            addCriterion("wide <=", value, "wide");
            return (Criteria) this;
        }

        public Criteria andWideIn(List<Integer> values) {
            addCriterion("wide in", values, "wide");
            return (Criteria) this;
        }

        public Criteria andWideNotIn(List<Integer> values) {
            addCriterion("wide not in", values, "wide");
            return (Criteria) this;
        }

        public Criteria andWideBetween(Integer value1, Integer value2) {
            addCriterion("wide between", value1, value2, "wide");
            return (Criteria) this;
        }

        public Criteria andWideNotBetween(Integer value1, Integer value2) {
            addCriterion("wide not between", value1, value2, "wide");
            return (Criteria) this;
        }

        public Criteria andHighIsNull() {
            addCriterion("high is null");
            return (Criteria) this;
        }

        public Criteria andHighIsNotNull() {
            addCriterion("high is not null");
            return (Criteria) this;
        }

        public Criteria andHighEqualTo(Integer value) {
            addCriterion("high =", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighNotEqualTo(Integer value) {
            addCriterion("high <>", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighGreaterThan(Integer value) {
            addCriterion("high >", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighGreaterThanOrEqualTo(Integer value) {
            addCriterion("high >=", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighLessThan(Integer value) {
            addCriterion("high <", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighLessThanOrEqualTo(Integer value) {
            addCriterion("high <=", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighIn(List<Integer> values) {
            addCriterion("high in", values, "high");
            return (Criteria) this;
        }

        public Criteria andHighNotIn(List<Integer> values) {
            addCriterion("high not in", values, "high");
            return (Criteria) this;
        }

        public Criteria andHighBetween(Integer value1, Integer value2) {
            addCriterion("high between", value1, value2, "high");
            return (Criteria) this;
        }

        public Criteria andHighNotBetween(Integer value1, Integer value2) {
            addCriterion("high not between", value1, value2, "high");
            return (Criteria) this;
        }

        public Criteria andAllowWeightIsNull() {
            addCriterion("allow_weight is null");
            return (Criteria) this;
        }

        public Criteria andAllowWeightIsNotNull() {
            addCriterion("allow_weight is not null");
            return (Criteria) this;
        }

        public Criteria andAllowWeightEqualTo(Integer value) {
            addCriterion("allow_weight =", value, "allowWeight");
            return (Criteria) this;
        }

        public Criteria andAllowWeightNotEqualTo(Integer value) {
            addCriterion("allow_weight <>", value, "allowWeight");
            return (Criteria) this;
        }

        public Criteria andAllowWeightGreaterThan(Integer value) {
            addCriterion("allow_weight >", value, "allowWeight");
            return (Criteria) this;
        }

        public Criteria andAllowWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("allow_weight >=", value, "allowWeight");
            return (Criteria) this;
        }

        public Criteria andAllowWeightLessThan(Integer value) {
            addCriterion("allow_weight <", value, "allowWeight");
            return (Criteria) this;
        }

        public Criteria andAllowWeightLessThanOrEqualTo(Integer value) {
            addCriterion("allow_weight <=", value, "allowWeight");
            return (Criteria) this;
        }

        public Criteria andAllowWeightIn(List<Integer> values) {
            addCriterion("allow_weight in", values, "allowWeight");
            return (Criteria) this;
        }

        public Criteria andAllowWeightNotIn(List<Integer> values) {
            addCriterion("allow_weight not in", values, "allowWeight");
            return (Criteria) this;
        }

        public Criteria andAllowWeightBetween(Integer value1, Integer value2) {
            addCriterion("allow_weight between", value1, value2, "allowWeight");
            return (Criteria) this;
        }

        public Criteria andAllowWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("allow_weight not between", value1, value2, "allowWeight");
            return (Criteria) this;
        }

        public Criteria andWeighIsNull() {
            addCriterion("weigh is null");
            return (Criteria) this;
        }

        public Criteria andWeighIsNotNull() {
            addCriterion("weigh is not null");
            return (Criteria) this;
        }

        public Criteria andWeighEqualTo(Integer value) {
            addCriterion("weigh =", value, "weigh");
            return (Criteria) this;
        }

        public Criteria andWeighNotEqualTo(Integer value) {
            addCriterion("weigh <>", value, "weigh");
            return (Criteria) this;
        }

        public Criteria andWeighGreaterThan(Integer value) {
            addCriterion("weigh >", value, "weigh");
            return (Criteria) this;
        }

        public Criteria andWeighGreaterThanOrEqualTo(Integer value) {
            addCriterion("weigh >=", value, "weigh");
            return (Criteria) this;
        }

        public Criteria andWeighLessThan(Integer value) {
            addCriterion("weigh <", value, "weigh");
            return (Criteria) this;
        }

        public Criteria andWeighLessThanOrEqualTo(Integer value) {
            addCriterion("weigh <=", value, "weigh");
            return (Criteria) this;
        }

        public Criteria andWeighIn(List<Integer> values) {
            addCriterion("weigh in", values, "weigh");
            return (Criteria) this;
        }

        public Criteria andWeighNotIn(List<Integer> values) {
            addCriterion("weigh not in", values, "weigh");
            return (Criteria) this;
        }

        public Criteria andWeighBetween(Integer value1, Integer value2) {
            addCriterion("weigh between", value1, value2, "weigh");
            return (Criteria) this;
        }

        public Criteria andWeighNotBetween(Integer value1, Integer value2) {
            addCriterion("weigh not between", value1, value2, "weigh");
            return (Criteria) this;
        }

        public Criteria andTotalWeiIsNull() {
            addCriterion("total_wei is null");
            return (Criteria) this;
        }

        public Criteria andTotalWeiIsNotNull() {
            addCriterion("total_wei is not null");
            return (Criteria) this;
        }

        public Criteria andTotalWeiEqualTo(Integer value) {
            addCriterion("total_wei =", value, "totalWei");
            return (Criteria) this;
        }

        public Criteria andTotalWeiNotEqualTo(Integer value) {
            addCriterion("total_wei <>", value, "totalWei");
            return (Criteria) this;
        }

        public Criteria andTotalWeiGreaterThan(Integer value) {
            addCriterion("total_wei >", value, "totalWei");
            return (Criteria) this;
        }

        public Criteria andTotalWeiGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_wei >=", value, "totalWei");
            return (Criteria) this;
        }

        public Criteria andTotalWeiLessThan(Integer value) {
            addCriterion("total_wei <", value, "totalWei");
            return (Criteria) this;
        }

        public Criteria andTotalWeiLessThanOrEqualTo(Integer value) {
            addCriterion("total_wei <=", value, "totalWei");
            return (Criteria) this;
        }

        public Criteria andTotalWeiIn(List<Integer> values) {
            addCriterion("total_wei in", values, "totalWei");
            return (Criteria) this;
        }

        public Criteria andTotalWeiNotIn(List<Integer> values) {
            addCriterion("total_wei not in", values, "totalWei");
            return (Criteria) this;
        }

        public Criteria andTotalWeiBetween(Integer value1, Integer value2) {
            addCriterion("total_wei between", value1, value2, "totalWei");
            return (Criteria) this;
        }

        public Criteria andTotalWeiNotBetween(Integer value1, Integer value2) {
            addCriterion("total_wei not between", value1, value2, "totalWei");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andOwnTypeIsNull() {
            addCriterion("own_type is null");
            return (Criteria) this;
        }

        public Criteria andOwnTypeIsNotNull() {
            addCriterion("own_type is not null");
            return (Criteria) this;
        }

        public Criteria andOwnTypeEqualTo(String value) {
            addCriterion("own_type =", value, "ownType");
            return (Criteria) this;
        }

        public Criteria andOwnTypeNotEqualTo(String value) {
            addCriterion("own_type <>", value, "ownType");
            return (Criteria) this;
        }

        public Criteria andOwnTypeGreaterThan(String value) {
            addCriterion("own_type >", value, "ownType");
            return (Criteria) this;
        }

        public Criteria andOwnTypeGreaterThanOrEqualTo(String value) {
            addCriterion("own_type >=", value, "ownType");
            return (Criteria) this;
        }

        public Criteria andOwnTypeLessThan(String value) {
            addCriterion("own_type <", value, "ownType");
            return (Criteria) this;
        }

        public Criteria andOwnTypeLessThanOrEqualTo(String value) {
            addCriterion("own_type <=", value, "ownType");
            return (Criteria) this;
        }

        public Criteria andOwnTypeLike(String value) {
            addCriterion("own_type like", value, "ownType");
            return (Criteria) this;
        }

        public Criteria andOwnTypeNotLike(String value) {
            addCriterion("own_type not like", value, "ownType");
            return (Criteria) this;
        }

        public Criteria andOwnTypeIn(List<String> values) {
            addCriterion("own_type in", values, "ownType");
            return (Criteria) this;
        }

        public Criteria andOwnTypeNotIn(List<String> values) {
            addCriterion("own_type not in", values, "ownType");
            return (Criteria) this;
        }

        public Criteria andOwnTypeBetween(String value1, String value2) {
            addCriterion("own_type between", value1, value2, "ownType");
            return (Criteria) this;
        }

        public Criteria andOwnTypeNotBetween(String value1, String value2) {
            addCriterion("own_type not between", value1, value2, "ownType");
            return (Criteria) this;
        }

        public Criteria andCertNumIsNull() {
            addCriterion("cert_num is null");
            return (Criteria) this;
        }

        public Criteria andCertNumIsNotNull() {
            addCriterion("cert_num is not null");
            return (Criteria) this;
        }

        public Criteria andCertNumEqualTo(String value) {
            addCriterion("cert_num =", value, "certNum");
            return (Criteria) this;
        }

        public Criteria andCertNumNotEqualTo(String value) {
            addCriterion("cert_num <>", value, "certNum");
            return (Criteria) this;
        }

        public Criteria andCertNumGreaterThan(String value) {
            addCriterion("cert_num >", value, "certNum");
            return (Criteria) this;
        }

        public Criteria andCertNumGreaterThanOrEqualTo(String value) {
            addCriterion("cert_num >=", value, "certNum");
            return (Criteria) this;
        }

        public Criteria andCertNumLessThan(String value) {
            addCriterion("cert_num <", value, "certNum");
            return (Criteria) this;
        }

        public Criteria andCertNumLessThanOrEqualTo(String value) {
            addCriterion("cert_num <=", value, "certNum");
            return (Criteria) this;
        }

        public Criteria andCertNumLike(String value) {
            addCriterion("cert_num like", value, "certNum");
            return (Criteria) this;
        }

        public Criteria andCertNumNotLike(String value) {
            addCriterion("cert_num not like", value, "certNum");
            return (Criteria) this;
        }

        public Criteria andCertNumIn(List<String> values) {
            addCriterion("cert_num in", values, "certNum");
            return (Criteria) this;
        }

        public Criteria andCertNumNotIn(List<String> values) {
            addCriterion("cert_num not in", values, "certNum");
            return (Criteria) this;
        }

        public Criteria andCertNumBetween(String value1, String value2) {
            addCriterion("cert_num between", value1, value2, "certNum");
            return (Criteria) this;
        }

        public Criteria andCertNumNotBetween(String value1, String value2) {
            addCriterion("cert_num not between", value1, value2, "certNum");
            return (Criteria) this;
        }

        public Criteria andScopeIsNull() {
            addCriterion("scope is null");
            return (Criteria) this;
        }

        public Criteria andScopeIsNotNull() {
            addCriterion("scope is not null");
            return (Criteria) this;
        }

        public Criteria andScopeEqualTo(String value) {
            addCriterion("scope =", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotEqualTo(String value) {
            addCriterion("scope <>", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeGreaterThan(String value) {
            addCriterion("scope >", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeGreaterThanOrEqualTo(String value) {
            addCriterion("scope >=", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLessThan(String value) {
            addCriterion("scope <", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLessThanOrEqualTo(String value) {
            addCriterion("scope <=", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLike(String value) {
            addCriterion("scope like", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotLike(String value) {
            addCriterion("scope not like", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeIn(List<String> values) {
            addCriterion("scope in", values, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotIn(List<String> values) {
            addCriterion("scope not in", values, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeBetween(String value1, String value2) {
            addCriterion("scope between", value1, value2, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotBetween(String value1, String value2) {
            addCriterion("scope not between", value1, value2, "scope");
            return (Criteria) this;
        }

        public Criteria andInsuranceDateIsNull() {
            addCriterion("insurance_date is null");
            return (Criteria) this;
        }

        public Criteria andInsuranceDateIsNotNull() {
            addCriterion("insurance_date is not null");
            return (Criteria) this;
        }

        public Criteria andInsuranceDateEqualTo(Date value) {
            addCriterionForJDBCDate("insurance_date =", value, "insuranceDate");
            return (Criteria) this;
        }

        public Criteria andInsuranceDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("insurance_date <>", value, "insuranceDate");
            return (Criteria) this;
        }

        public Criteria andInsuranceDateGreaterThan(Date value) {
            addCriterionForJDBCDate("insurance_date >", value, "insuranceDate");
            return (Criteria) this;
        }

        public Criteria andInsuranceDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("insurance_date >=", value, "insuranceDate");
            return (Criteria) this;
        }

        public Criteria andInsuranceDateLessThan(Date value) {
            addCriterionForJDBCDate("insurance_date <", value, "insuranceDate");
            return (Criteria) this;
        }

        public Criteria andInsuranceDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("insurance_date <=", value, "insuranceDate");
            return (Criteria) this;
        }

        public Criteria andInsuranceDateIn(List<Date> values) {
            addCriterionForJDBCDate("insurance_date in", values, "insuranceDate");
            return (Criteria) this;
        }

        public Criteria andInsuranceDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("insurance_date not in", values, "insuranceDate");
            return (Criteria) this;
        }

        public Criteria andInsuranceDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("insurance_date between", value1, value2, "insuranceDate");
            return (Criteria) this;
        }

        public Criteria andInsuranceDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("insurance_date not between", value1, value2, "insuranceDate");
            return (Criteria) this;
        }

        public Criteria andDutyInsurancedateIsNull() {
            addCriterion("duty_insurancedate is null");
            return (Criteria) this;
        }

        public Criteria andDutyInsurancedateIsNotNull() {
            addCriterion("duty_insurancedate is not null");
            return (Criteria) this;
        }

        public Criteria andDutyInsurancedateEqualTo(Date value) {
            addCriterionForJDBCDate("duty_insurancedate =", value, "dutyInsurancedate");
            return (Criteria) this;
        }

        public Criteria andDutyInsurancedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("duty_insurancedate <>", value, "dutyInsurancedate");
            return (Criteria) this;
        }

        public Criteria andDutyInsurancedateGreaterThan(Date value) {
            addCriterionForJDBCDate("duty_insurancedate >", value, "dutyInsurancedate");
            return (Criteria) this;
        }

        public Criteria andDutyInsurancedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("duty_insurancedate >=", value, "dutyInsurancedate");
            return (Criteria) this;
        }

        public Criteria andDutyInsurancedateLessThan(Date value) {
            addCriterionForJDBCDate("duty_insurancedate <", value, "dutyInsurancedate");
            return (Criteria) this;
        }

        public Criteria andDutyInsurancedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("duty_insurancedate <=", value, "dutyInsurancedate");
            return (Criteria) this;
        }

        public Criteria andDutyInsurancedateIn(List<Date> values) {
            addCriterionForJDBCDate("duty_insurancedate in", values, "dutyInsurancedate");
            return (Criteria) this;
        }

        public Criteria andDutyInsurancedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("duty_insurancedate not in", values, "dutyInsurancedate");
            return (Criteria) this;
        }

        public Criteria andDutyInsurancedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("duty_insurancedate between", value1, value2, "dutyInsurancedate");
            return (Criteria) this;
        }

        public Criteria andDutyInsurancedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("duty_insurancedate not between", value1, value2, "dutyInsurancedate");
            return (Criteria) this;
        }

        public Criteria andDutypeoDateIsNull() {
            addCriterion("dutypeo_date is null");
            return (Criteria) this;
        }

        public Criteria andDutypeoDateIsNotNull() {
            addCriterion("dutypeo_date is not null");
            return (Criteria) this;
        }

        public Criteria andDutypeoDateEqualTo(Date value) {
            addCriterionForJDBCDate("dutypeo_date =", value, "dutypeoDate");
            return (Criteria) this;
        }

        public Criteria andDutypeoDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("dutypeo_date <>", value, "dutypeoDate");
            return (Criteria) this;
        }

        public Criteria andDutypeoDateGreaterThan(Date value) {
            addCriterionForJDBCDate("dutypeo_date >", value, "dutypeoDate");
            return (Criteria) this;
        }

        public Criteria andDutypeoDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("dutypeo_date >=", value, "dutypeoDate");
            return (Criteria) this;
        }

        public Criteria andDutypeoDateLessThan(Date value) {
            addCriterionForJDBCDate("dutypeo_date <", value, "dutypeoDate");
            return (Criteria) this;
        }

        public Criteria andDutypeoDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("dutypeo_date <=", value, "dutypeoDate");
            return (Criteria) this;
        }

        public Criteria andDutypeoDateIn(List<Date> values) {
            addCriterionForJDBCDate("dutypeo_date in", values, "dutypeoDate");
            return (Criteria) this;
        }

        public Criteria andDutypeoDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("dutypeo_date not in", values, "dutypeoDate");
            return (Criteria) this;
        }

        public Criteria andDutypeoDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("dutypeo_date between", value1, value2, "dutypeoDate");
            return (Criteria) this;
        }

        public Criteria andDutypeoDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("dutypeo_date not between", value1, value2, "dutypeoDate");
            return (Criteria) this;
        }

        public Criteria andSatelliteIsNull() {
            addCriterion("satellite is null");
            return (Criteria) this;
        }

        public Criteria andSatelliteIsNotNull() {
            addCriterion("satellite is not null");
            return (Criteria) this;
        }

        public Criteria andSatelliteEqualTo(String value) {
            addCriterion("satellite =", value, "satellite");
            return (Criteria) this;
        }

        public Criteria andSatelliteNotEqualTo(String value) {
            addCriterion("satellite <>", value, "satellite");
            return (Criteria) this;
        }

        public Criteria andSatelliteGreaterThan(String value) {
            addCriterion("satellite >", value, "satellite");
            return (Criteria) this;
        }

        public Criteria andSatelliteGreaterThanOrEqualTo(String value) {
            addCriterion("satellite >=", value, "satellite");
            return (Criteria) this;
        }

        public Criteria andSatelliteLessThan(String value) {
            addCriterion("satellite <", value, "satellite");
            return (Criteria) this;
        }

        public Criteria andSatelliteLessThanOrEqualTo(String value) {
            addCriterion("satellite <=", value, "satellite");
            return (Criteria) this;
        }

        public Criteria andSatelliteLike(String value) {
            addCriterion("satellite like", value, "satellite");
            return (Criteria) this;
        }

        public Criteria andSatelliteNotLike(String value) {
            addCriterion("satellite not like", value, "satellite");
            return (Criteria) this;
        }

        public Criteria andSatelliteIn(List<String> values) {
            addCriterion("satellite in", values, "satellite");
            return (Criteria) this;
        }

        public Criteria andSatelliteNotIn(List<String> values) {
            addCriterion("satellite not in", values, "satellite");
            return (Criteria) this;
        }

        public Criteria andSatelliteBetween(String value1, String value2) {
            addCriterion("satellite between", value1, value2, "satellite");
            return (Criteria) this;
        }

        public Criteria andSatelliteNotBetween(String value1, String value2) {
            addCriterion("satellite not between", value1, value2, "satellite");
            return (Criteria) this;
        }

        public Criteria andRoadDateIsNull() {
            addCriterion("road_date is null");
            return (Criteria) this;
        }

        public Criteria andRoadDateIsNotNull() {
            addCriterion("road_date is not null");
            return (Criteria) this;
        }

        public Criteria andRoadDateEqualTo(Date value) {
            addCriterionForJDBCDate("road_date =", value, "roadDate");
            return (Criteria) this;
        }

        public Criteria andRoadDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("road_date <>", value, "roadDate");
            return (Criteria) this;
        }

        public Criteria andRoadDateGreaterThan(Date value) {
            addCriterionForJDBCDate("road_date >", value, "roadDate");
            return (Criteria) this;
        }

        public Criteria andRoadDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("road_date >=", value, "roadDate");
            return (Criteria) this;
        }

        public Criteria andRoadDateLessThan(Date value) {
            addCriterionForJDBCDate("road_date <", value, "roadDate");
            return (Criteria) this;
        }

        public Criteria andRoadDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("road_date <=", value, "roadDate");
            return (Criteria) this;
        }

        public Criteria andRoadDateIn(List<Date> values) {
            addCriterionForJDBCDate("road_date in", values, "roadDate");
            return (Criteria) this;
        }

        public Criteria andRoadDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("road_date not in", values, "roadDate");
            return (Criteria) this;
        }

        public Criteria andRoadDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("road_date between", value1, value2, "roadDate");
            return (Criteria) this;
        }

        public Criteria andRoadDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("road_date not between", value1, value2, "roadDate");
            return (Criteria) this;
        }

        public Criteria andCertDateIsNull() {
            addCriterion("cert_date is null");
            return (Criteria) this;
        }

        public Criteria andCertDateIsNotNull() {
            addCriterion("cert_date is not null");
            return (Criteria) this;
        }

        public Criteria andCertDateEqualTo(Date value) {
            addCriterionForJDBCDate("cert_date =", value, "certDate");
            return (Criteria) this;
        }

        public Criteria andCertDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("cert_date <>", value, "certDate");
            return (Criteria) this;
        }

        public Criteria andCertDateGreaterThan(Date value) {
            addCriterionForJDBCDate("cert_date >", value, "certDate");
            return (Criteria) this;
        }

        public Criteria andCertDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("cert_date >=", value, "certDate");
            return (Criteria) this;
        }

        public Criteria andCertDateLessThan(Date value) {
            addCriterionForJDBCDate("cert_date <", value, "certDate");
            return (Criteria) this;
        }

        public Criteria andCertDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("cert_date <=", value, "certDate");
            return (Criteria) this;
        }

        public Criteria andCertDateIn(List<Date> values) {
            addCriterionForJDBCDate("cert_date in", values, "certDate");
            return (Criteria) this;
        }

        public Criteria andCertDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("cert_date not in", values, "certDate");
            return (Criteria) this;
        }

        public Criteria andCertDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("cert_date between", value1, value2, "certDate");
            return (Criteria) this;
        }

        public Criteria andCertDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("cert_date not between", value1, value2, "certDate");
            return (Criteria) this;
        }

        public Criteria andCertyearDateIsNull() {
            addCriterion("certyear_date is null");
            return (Criteria) this;
        }

        public Criteria andCertyearDateIsNotNull() {
            addCriterion("certyear_date is not null");
            return (Criteria) this;
        }

        public Criteria andCertyearDateEqualTo(Date value) {
            addCriterionForJDBCDate("certyear_date =", value, "certyearDate");
            return (Criteria) this;
        }

        public Criteria andCertyearDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("certyear_date <>", value, "certyearDate");
            return (Criteria) this;
        }

        public Criteria andCertyearDateGreaterThan(Date value) {
            addCriterionForJDBCDate("certyear_date >", value, "certyearDate");
            return (Criteria) this;
        }

        public Criteria andCertyearDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("certyear_date >=", value, "certyearDate");
            return (Criteria) this;
        }

        public Criteria andCertyearDateLessThan(Date value) {
            addCriterionForJDBCDate("certyear_date <", value, "certyearDate");
            return (Criteria) this;
        }

        public Criteria andCertyearDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("certyear_date <=", value, "certyearDate");
            return (Criteria) this;
        }

        public Criteria andCertyearDateIn(List<Date> values) {
            addCriterionForJDBCDate("certyear_date in", values, "certyearDate");
            return (Criteria) this;
        }

        public Criteria andCertyearDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("certyear_date not in", values, "certyearDate");
            return (Criteria) this;
        }

        public Criteria andCertyearDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("certyear_date between", value1, value2, "certyearDate");
            return (Criteria) this;
        }

        public Criteria andCertyearDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("certyear_date not between", value1, value2, "certyearDate");
            return (Criteria) this;
        }

        public Criteria andCertagrDateIsNull() {
            addCriterion("certagr_date is null");
            return (Criteria) this;
        }

        public Criteria andCertagrDateIsNotNull() {
            addCriterion("certagr_date is not null");
            return (Criteria) this;
        }

        public Criteria andCertagrDateEqualTo(Date value) {
            addCriterionForJDBCDate("certagr_date =", value, "certagrDate");
            return (Criteria) this;
        }

        public Criteria andCertagrDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("certagr_date <>", value, "certagrDate");
            return (Criteria) this;
        }

        public Criteria andCertagrDateGreaterThan(Date value) {
            addCriterionForJDBCDate("certagr_date >", value, "certagrDate");
            return (Criteria) this;
        }

        public Criteria andCertagrDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("certagr_date >=", value, "certagrDate");
            return (Criteria) this;
        }

        public Criteria andCertagrDateLessThan(Date value) {
            addCriterionForJDBCDate("certagr_date <", value, "certagrDate");
            return (Criteria) this;
        }

        public Criteria andCertagrDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("certagr_date <=", value, "certagrDate");
            return (Criteria) this;
        }

        public Criteria andCertagrDateIn(List<Date> values) {
            addCriterionForJDBCDate("certagr_date in", values, "certagrDate");
            return (Criteria) this;
        }

        public Criteria andCertagrDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("certagr_date not in", values, "certagrDate");
            return (Criteria) this;
        }

        public Criteria andCertagrDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("certagr_date between", value1, value2, "certagrDate");
            return (Criteria) this;
        }

        public Criteria andCertagrDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("certagr_date not between", value1, value2, "certagrDate");
            return (Criteria) this;
        }

        public Criteria andYearcheckDateIsNull() {
            addCriterion("yearcheck_date is null");
            return (Criteria) this;
        }

        public Criteria andYearcheckDateIsNotNull() {
            addCriterion("yearcheck_date is not null");
            return (Criteria) this;
        }

        public Criteria andYearcheckDateEqualTo(Date value) {
            addCriterionForJDBCDate("yearcheck_date =", value, "yearcheckDate");
            return (Criteria) this;
        }

        public Criteria andYearcheckDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("yearcheck_date <>", value, "yearcheckDate");
            return (Criteria) this;
        }

        public Criteria andYearcheckDateGreaterThan(Date value) {
            addCriterionForJDBCDate("yearcheck_date >", value, "yearcheckDate");
            return (Criteria) this;
        }

        public Criteria andYearcheckDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("yearcheck_date >=", value, "yearcheckDate");
            return (Criteria) this;
        }

        public Criteria andYearcheckDateLessThan(Date value) {
            addCriterionForJDBCDate("yearcheck_date <", value, "yearcheckDate");
            return (Criteria) this;
        }

        public Criteria andYearcheckDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("yearcheck_date <=", value, "yearcheckDate");
            return (Criteria) this;
        }

        public Criteria andYearcheckDateIn(List<Date> values) {
            addCriterionForJDBCDate("yearcheck_date in", values, "yearcheckDate");
            return (Criteria) this;
        }

        public Criteria andYearcheckDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("yearcheck_date not in", values, "yearcheckDate");
            return (Criteria) this;
        }

        public Criteria andYearcheckDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("yearcheck_date between", value1, value2, "yearcheckDate");
            return (Criteria) this;
        }

        public Criteria andYearcheckDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("yearcheck_date not between", value1, value2, "yearcheckDate");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNull() {
            addCriterion("volume is null");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNotNull() {
            addCriterion("volume is not null");
            return (Criteria) this;
        }

        public Criteria andVolumeEqualTo(Integer value) {
            addCriterion("volume =", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotEqualTo(Integer value) {
            addCriterion("volume <>", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThan(Integer value) {
            addCriterion("volume >", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThanOrEqualTo(Integer value) {
            addCriterion("volume >=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThan(Integer value) {
            addCriterion("volume <", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThanOrEqualTo(Integer value) {
            addCriterion("volume <=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeIn(List<Integer> values) {
            addCriterion("volume in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotIn(List<Integer> values) {
            addCriterion("volume not in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeBetween(Integer value1, Integer value2) {
            addCriterion("volume between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotBetween(Integer value1, Integer value2) {
            addCriterion("volume not between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andQualityIsNull() {
            addCriterion("quality is null");
            return (Criteria) this;
        }

        public Criteria andQualityIsNotNull() {
            addCriterion("quality is not null");
            return (Criteria) this;
        }

        public Criteria andQualityEqualTo(String value) {
            addCriterion("quality =", value, "quality");
            return (Criteria) this;
        }

        public Criteria andQualityNotEqualTo(String value) {
            addCriterion("quality <>", value, "quality");
            return (Criteria) this;
        }

        public Criteria andQualityGreaterThan(String value) {
            addCriterion("quality >", value, "quality");
            return (Criteria) this;
        }

        public Criteria andQualityGreaterThanOrEqualTo(String value) {
            addCriterion("quality >=", value, "quality");
            return (Criteria) this;
        }

        public Criteria andQualityLessThan(String value) {
            addCriterion("quality <", value, "quality");
            return (Criteria) this;
        }

        public Criteria andQualityLessThanOrEqualTo(String value) {
            addCriterion("quality <=", value, "quality");
            return (Criteria) this;
        }

        public Criteria andQualityLike(String value) {
            addCriterion("quality like", value, "quality");
            return (Criteria) this;
        }

        public Criteria andQualityNotLike(String value) {
            addCriterion("quality not like", value, "quality");
            return (Criteria) this;
        }

        public Criteria andQualityIn(List<String> values) {
            addCriterion("quality in", values, "quality");
            return (Criteria) this;
        }

        public Criteria andQualityNotIn(List<String> values) {
            addCriterion("quality not in", values, "quality");
            return (Criteria) this;
        }

        public Criteria andQualityBetween(String value1, String value2) {
            addCriterion("quality between", value1, value2, "quality");
            return (Criteria) this;
        }

        public Criteria andQualityNotBetween(String value1, String value2) {
            addCriterion("quality not between", value1, value2, "quality");
            return (Criteria) this;
        }

        public Criteria andTecDateIsNull() {
            addCriterion("tec_date is null");
            return (Criteria) this;
        }

        public Criteria andTecDateIsNotNull() {
            addCriterion("tec_date is not null");
            return (Criteria) this;
        }

        public Criteria andTecDateEqualTo(Date value) {
            addCriterionForJDBCDate("tec_date =", value, "tecDate");
            return (Criteria) this;
        }

        public Criteria andTecDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("tec_date <>", value, "tecDate");
            return (Criteria) this;
        }

        public Criteria andTecDateGreaterThan(Date value) {
            addCriterionForJDBCDate("tec_date >", value, "tecDate");
            return (Criteria) this;
        }

        public Criteria andTecDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("tec_date >=", value, "tecDate");
            return (Criteria) this;
        }

        public Criteria andTecDateLessThan(Date value) {
            addCriterionForJDBCDate("tec_date <", value, "tecDate");
            return (Criteria) this;
        }

        public Criteria andTecDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("tec_date <=", value, "tecDate");
            return (Criteria) this;
        }

        public Criteria andTecDateIn(List<Date> values) {
            addCriterionForJDBCDate("tec_date in", values, "tecDate");
            return (Criteria) this;
        }

        public Criteria andTecDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("tec_date not in", values, "tecDate");
            return (Criteria) this;
        }

        public Criteria andTecDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("tec_date between", value1, value2, "tecDate");
            return (Criteria) this;
        }

        public Criteria andTecDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("tec_date not between", value1, value2, "tecDate");
            return (Criteria) this;
        }

        public Criteria andSecImprovedateIsNull() {
            addCriterion("sec_improvedate is null");
            return (Criteria) this;
        }

        public Criteria andSecImprovedateIsNotNull() {
            addCriterion("sec_improvedate is not null");
            return (Criteria) this;
        }

        public Criteria andSecImprovedateEqualTo(Date value) {
            addCriterionForJDBCDate("sec_improvedate =", value, "secImprovedate");
            return (Criteria) this;
        }

        public Criteria andSecImprovedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("sec_improvedate <>", value, "secImprovedate");
            return (Criteria) this;
        }

        public Criteria andSecImprovedateGreaterThan(Date value) {
            addCriterionForJDBCDate("sec_improvedate >", value, "secImprovedate");
            return (Criteria) this;
        }

        public Criteria andSecImprovedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("sec_improvedate >=", value, "secImprovedate");
            return (Criteria) this;
        }

        public Criteria andSecImprovedateLessThan(Date value) {
            addCriterionForJDBCDate("sec_improvedate <", value, "secImprovedate");
            return (Criteria) this;
        }

        public Criteria andSecImprovedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("sec_improvedate <=", value, "secImprovedate");
            return (Criteria) this;
        }

        public Criteria andSecImprovedateIn(List<Date> values) {
            addCriterionForJDBCDate("sec_improvedate in", values, "secImprovedate");
            return (Criteria) this;
        }

        public Criteria andSecImprovedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("sec_improvedate not in", values, "secImprovedate");
            return (Criteria) this;
        }

        public Criteria andSecImprovedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("sec_improvedate between", value1, value2, "secImprovedate");
            return (Criteria) this;
        }

        public Criteria andSecImprovedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("sec_improvedate not between", value1, value2, "secImprovedate");
            return (Criteria) this;
        }

        public Criteria andDriverNameIsNull() {
            addCriterion("driver_name is null");
            return (Criteria) this;
        }

        public Criteria andDriverNameIsNotNull() {
            addCriterion("driver_name is not null");
            return (Criteria) this;
        }

        public Criteria andDriverNameEqualTo(String value) {
            addCriterion("driver_name =", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameNotEqualTo(String value) {
            addCriterion("driver_name <>", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameGreaterThan(String value) {
            addCriterion("driver_name >", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameGreaterThanOrEqualTo(String value) {
            addCriterion("driver_name >=", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameLessThan(String value) {
            addCriterion("driver_name <", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameLessThanOrEqualTo(String value) {
            addCriterion("driver_name <=", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameLike(String value) {
            addCriterion("driver_name like", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameNotLike(String value) {
            addCriterion("driver_name not like", value, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameIn(List<String> values) {
            addCriterion("driver_name in", values, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameNotIn(List<String> values) {
            addCriterion("driver_name not in", values, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameBetween(String value1, String value2) {
            addCriterion("driver_name between", value1, value2, "driverName");
            return (Criteria) this;
        }

        public Criteria andDriverNameNotBetween(String value1, String value2) {
            addCriterion("driver_name not between", value1, value2, "driverName");
            return (Criteria) this;
        }

        public Criteria andSaferIsNull() {
            addCriterion("safer is null");
            return (Criteria) this;
        }

        public Criteria andSaferIsNotNull() {
            addCriterion("safer is not null");
            return (Criteria) this;
        }

        public Criteria andSaferEqualTo(String value) {
            addCriterion("safer =", value, "safer");
            return (Criteria) this;
        }

        public Criteria andSaferNotEqualTo(String value) {
            addCriterion("safer <>", value, "safer");
            return (Criteria) this;
        }

        public Criteria andSaferGreaterThan(String value) {
            addCriterion("safer >", value, "safer");
            return (Criteria) this;
        }

        public Criteria andSaferGreaterThanOrEqualTo(String value) {
            addCriterion("safer >=", value, "safer");
            return (Criteria) this;
        }

        public Criteria andSaferLessThan(String value) {
            addCriterion("safer <", value, "safer");
            return (Criteria) this;
        }

        public Criteria andSaferLessThanOrEqualTo(String value) {
            addCriterion("safer <=", value, "safer");
            return (Criteria) this;
        }

        public Criteria andSaferLike(String value) {
            addCriterion("safer like", value, "safer");
            return (Criteria) this;
        }

        public Criteria andSaferNotLike(String value) {
            addCriterion("safer not like", value, "safer");
            return (Criteria) this;
        }

        public Criteria andSaferIn(List<String> values) {
            addCriterion("safer in", values, "safer");
            return (Criteria) this;
        }

        public Criteria andSaferNotIn(List<String> values) {
            addCriterion("safer not in", values, "safer");
            return (Criteria) this;
        }

        public Criteria andSaferBetween(String value1, String value2) {
            addCriterion("safer between", value1, value2, "safer");
            return (Criteria) this;
        }

        public Criteria andSaferNotBetween(String value1, String value2) {
            addCriterion("safer not between", value1, value2, "safer");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andReserveOneIsNull() {
            addCriterion("reserve_one is null");
            return (Criteria) this;
        }

        public Criteria andReserveOneIsNotNull() {
            addCriterion("reserve_one is not null");
            return (Criteria) this;
        }

        public Criteria andReserveOneEqualTo(String value) {
            addCriterion("reserve_one =", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotEqualTo(String value) {
            addCriterion("reserve_one <>", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneGreaterThan(String value) {
            addCriterion("reserve_one >", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_one >=", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneLessThan(String value) {
            addCriterion("reserve_one <", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneLessThanOrEqualTo(String value) {
            addCriterion("reserve_one <=", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneLike(String value) {
            addCriterion("reserve_one like", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotLike(String value) {
            addCriterion("reserve_one not like", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneIn(List<String> values) {
            addCriterion("reserve_one in", values, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotIn(List<String> values) {
            addCriterion("reserve_one not in", values, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneBetween(String value1, String value2) {
            addCriterion("reserve_one between", value1, value2, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotBetween(String value1, String value2) {
            addCriterion("reserve_one not between", value1, value2, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIsNull() {
            addCriterion("reserve_two is null");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIsNotNull() {
            addCriterion("reserve_two is not null");
            return (Criteria) this;
        }

        public Criteria andReserveTwoEqualTo(String value) {
            addCriterion("reserve_two =", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotEqualTo(String value) {
            addCriterion("reserve_two <>", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoGreaterThan(String value) {
            addCriterion("reserve_two >", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_two >=", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLessThan(String value) {
            addCriterion("reserve_two <", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLessThanOrEqualTo(String value) {
            addCriterion("reserve_two <=", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLike(String value) {
            addCriterion("reserve_two like", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotLike(String value) {
            addCriterion("reserve_two not like", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIn(List<String> values) {
            addCriterion("reserve_two in", values, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotIn(List<String> values) {
            addCriterion("reserve_two not in", values, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoBetween(String value1, String value2) {
            addCriterion("reserve_two between", value1, value2, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotBetween(String value1, String value2) {
            addCriterion("reserve_two not between", value1, value2, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveThreeIsNull() {
            addCriterion("reserve_three is null");
            return (Criteria) this;
        }

        public Criteria andReserveThreeIsNotNull() {
            addCriterion("reserve_three is not null");
            return (Criteria) this;
        }

        public Criteria andReserveThreeEqualTo(String value) {
            addCriterion("reserve_three =", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotEqualTo(String value) {
            addCriterion("reserve_three <>", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeGreaterThan(String value) {
            addCriterion("reserve_three >", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_three >=", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeLessThan(String value) {
            addCriterion("reserve_three <", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeLessThanOrEqualTo(String value) {
            addCriterion("reserve_three <=", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeLike(String value) {
            addCriterion("reserve_three like", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotLike(String value) {
            addCriterion("reserve_three not like", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeIn(List<String> values) {
            addCriterion("reserve_three in", values, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotIn(List<String> values) {
            addCriterion("reserve_three not in", values, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeBetween(String value1, String value2) {
            addCriterion("reserve_three between", value1, value2, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotBetween(String value1, String value2) {
            addCriterion("reserve_three not between", value1, value2, "reserveThree");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hl_carinfo
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 21 11:01:08 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}