package cm.cn.po;

public class HlCheckWaybill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.id
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.checkCar_array
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    private String checkcarArray;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.driverlog_array
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    private String driverlogArray;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.waybill_id
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    private Integer waybillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.reserve_one
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    private String reserveOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.reserve_two
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    private String reserveTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.reserve_three
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    private String reserveThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_check_waybill.waybill_state
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    private String waybillState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.id
     *
     * @return the value of hl_check_waybill.id
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.id
     *
     * @param id the value for hl_check_waybill.id
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.checkCar_array
     *
     * @return the value of hl_check_waybill.checkCar_array
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public String getCheckcarArray() {
        return checkcarArray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.checkCar_array
     *
     * @param checkcarArray the value for hl_check_waybill.checkCar_array
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public void setCheckcarArray(String checkcarArray) {
        this.checkcarArray = checkcarArray == null ? null : checkcarArray.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.driverlog_array
     *
     * @return the value of hl_check_waybill.driverlog_array
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public String getDriverlogArray() {
        return driverlogArray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.driverlog_array
     *
     * @param driverlogArray the value for hl_check_waybill.driverlog_array
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public void setDriverlogArray(String driverlogArray) {
        this.driverlogArray = driverlogArray == null ? null : driverlogArray.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.waybill_id
     *
     * @return the value of hl_check_waybill.waybill_id
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public Integer getWaybillId() {
        return waybillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.waybill_id
     *
     * @param waybillId the value for hl_check_waybill.waybill_id
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public void setWaybillId(Integer waybillId) {
        this.waybillId = waybillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.reserve_one
     *
     * @return the value of hl_check_waybill.reserve_one
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public String getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.reserve_one
     *
     * @param reserveOne the value for hl_check_waybill.reserve_one
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public void setReserveOne(String reserveOne) {
        this.reserveOne = reserveOne == null ? null : reserveOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.reserve_two
     *
     * @return the value of hl_check_waybill.reserve_two
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.reserve_two
     *
     * @param reserveTwo the value for hl_check_waybill.reserve_two
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo == null ? null : reserveTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.reserve_three
     *
     * @return the value of hl_check_waybill.reserve_three
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public String getReserveThree() {
        return reserveThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.reserve_three
     *
     * @param reserveThree the value for hl_check_waybill.reserve_three
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public void setReserveThree(String reserveThree) {
        this.reserveThree = reserveThree == null ? null : reserveThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_check_waybill.waybill_state
     *
     * @return the value of hl_check_waybill.waybill_state
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public String getWaybillState() {
        return waybillState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_check_waybill.waybill_state
     *
     * @param waybillState the value for hl_check_waybill.waybill_state
     *
     * @mbggenerated Thu Sep 28 11:49:35 CST 2017
     */
    public void setWaybillState(String waybillState) {
        this.waybillState = waybillState == null ? null : waybillState.trim();
    }
}