package cm.cn.po;

public class HlGoodsinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_goodsinfo.id
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_goodsinfo.code
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_goodsinfo.name
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_goodsinfo.goodstyle_id
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    private Integer goodstyleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_goodsinfo.safecard_id
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    private Integer safecardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_goodsinfo.remark
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_goodsinfo.reserve_one
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    private String reserveOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_goodsinfo.reserve_two
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    private String reserveTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_goodsinfo.reserve_three
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    private String reserveThree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_goodsinfo.id
     *
     * @return the value of hl_goodsinfo.id
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_goodsinfo.id
     *
     * @param id the value for hl_goodsinfo.id
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_goodsinfo.code
     *
     * @return the value of hl_goodsinfo.code
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_goodsinfo.code
     *
     * @param code the value for hl_goodsinfo.code
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_goodsinfo.name
     *
     * @return the value of hl_goodsinfo.name
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_goodsinfo.name
     *
     * @param name the value for hl_goodsinfo.name
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_goodsinfo.goodstyle_id
     *
     * @return the value of hl_goodsinfo.goodstyle_id
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public Integer getGoodstyleId() {
        return goodstyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_goodsinfo.goodstyle_id
     *
     * @param goodstyleId the value for hl_goodsinfo.goodstyle_id
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public void setGoodstyleId(Integer goodstyleId) {
        this.goodstyleId = goodstyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_goodsinfo.safecard_id
     *
     * @return the value of hl_goodsinfo.safecard_id
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public Integer getSafecardId() {
        return safecardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_goodsinfo.safecard_id
     *
     * @param safecardId the value for hl_goodsinfo.safecard_id
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public void setSafecardId(Integer safecardId) {
        this.safecardId = safecardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_goodsinfo.remark
     *
     * @return the value of hl_goodsinfo.remark
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_goodsinfo.remark
     *
     * @param remark the value for hl_goodsinfo.remark
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_goodsinfo.reserve_one
     *
     * @return the value of hl_goodsinfo.reserve_one
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public String getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_goodsinfo.reserve_one
     *
     * @param reserveOne the value for hl_goodsinfo.reserve_one
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public void setReserveOne(String reserveOne) {
        this.reserveOne = reserveOne == null ? null : reserveOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_goodsinfo.reserve_two
     *
     * @return the value of hl_goodsinfo.reserve_two
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_goodsinfo.reserve_two
     *
     * @param reserveTwo the value for hl_goodsinfo.reserve_two
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo == null ? null : reserveTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_goodsinfo.reserve_three
     *
     * @return the value of hl_goodsinfo.reserve_three
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public String getReserveThree() {
        return reserveThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_goodsinfo.reserve_three
     *
     * @param reserveThree the value for hl_goodsinfo.reserve_three
     *
     * @mbggenerated Tue Sep 12 11:21:55 CST 2017
     */
    public void setReserveThree(String reserveThree) {
        this.reserveThree = reserveThree == null ? null : reserveThree.trim();
    }
}