package cm.cn.po;

public class HlPeixun {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_peixun.id
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_peixun.name
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_peixun.url
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_peixun.createtime
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_peixun.theme
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_peixun.reserve_one
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    private String reserveOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_peixun.reserve_two
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    private String reserveTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_peixun.reserve_three
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    private String reserveThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_peixun.peixun_time
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    private Integer peixunTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_peixun.id
     *
     * @return the value of hl_peixun.id
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_peixun.id
     *
     * @param id the value for hl_peixun.id
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_peixun.name
     *
     * @return the value of hl_peixun.name
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_peixun.name
     *
     * @param name the value for hl_peixun.name
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_peixun.url
     *
     * @return the value of hl_peixun.url
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_peixun.url
     *
     * @param url the value for hl_peixun.url
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_peixun.createtime
     *
     * @return the value of hl_peixun.createtime
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_peixun.createtime
     *
     * @param createtime the value for hl_peixun.createtime
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_peixun.theme
     *
     * @return the value of hl_peixun.theme
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_peixun.theme
     *
     * @param theme the value for hl_peixun.theme
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_peixun.reserve_one
     *
     * @return the value of hl_peixun.reserve_one
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public String getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_peixun.reserve_one
     *
     * @param reserveOne the value for hl_peixun.reserve_one
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public void setReserveOne(String reserveOne) {
        this.reserveOne = reserveOne == null ? null : reserveOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_peixun.reserve_two
     *
     * @return the value of hl_peixun.reserve_two
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_peixun.reserve_two
     *
     * @param reserveTwo the value for hl_peixun.reserve_two
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo == null ? null : reserveTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_peixun.reserve_three
     *
     * @return the value of hl_peixun.reserve_three
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public String getReserveThree() {
        return reserveThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_peixun.reserve_three
     *
     * @param reserveThree the value for hl_peixun.reserve_three
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public void setReserveThree(String reserveThree) {
        this.reserveThree = reserveThree == null ? null : reserveThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_peixun.peixun_time
     *
     * @return the value of hl_peixun.peixun_time
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public Integer getPeixunTime() {
        return peixunTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_peixun.peixun_time
     *
     * @param peixunTime the value for hl_peixun.peixun_time
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    public void setPeixunTime(Integer peixunTime) {
        this.peixunTime = peixunTime;
    }
}