package cm.cn.po;

import java.util.ArrayList;
import java.util.List;

public class HlPeixunstateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    public HlPeixunstateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPeixunnameIsNull() {
            addCriterion("peixunname is null");
            return (Criteria) this;
        }

        public Criteria andPeixunnameIsNotNull() {
            addCriterion("peixunname is not null");
            return (Criteria) this;
        }

        public Criteria andPeixunnameEqualTo(String value) {
            addCriterion("peixunname =", value, "peixunname");
            return (Criteria) this;
        }

        public Criteria andPeixunnameNotEqualTo(String value) {
            addCriterion("peixunname <>", value, "peixunname");
            return (Criteria) this;
        }

        public Criteria andPeixunnameGreaterThan(String value) {
            addCriterion("peixunname >", value, "peixunname");
            return (Criteria) this;
        }

        public Criteria andPeixunnameGreaterThanOrEqualTo(String value) {
            addCriterion("peixunname >=", value, "peixunname");
            return (Criteria) this;
        }

        public Criteria andPeixunnameLessThan(String value) {
            addCriterion("peixunname <", value, "peixunname");
            return (Criteria) this;
        }

        public Criteria andPeixunnameLessThanOrEqualTo(String value) {
            addCriterion("peixunname <=", value, "peixunname");
            return (Criteria) this;
        }

        public Criteria andPeixunnameLike(String value) {
            addCriterion("peixunname like", value, "peixunname");
            return (Criteria) this;
        }

        public Criteria andPeixunnameNotLike(String value) {
            addCriterion("peixunname not like", value, "peixunname");
            return (Criteria) this;
        }

        public Criteria andPeixunnameIn(List<String> values) {
            addCriterion("peixunname in", values, "peixunname");
            return (Criteria) this;
        }

        public Criteria andPeixunnameNotIn(List<String> values) {
            addCriterion("peixunname not in", values, "peixunname");
            return (Criteria) this;
        }

        public Criteria andPeixunnameBetween(String value1, String value2) {
            addCriterion("peixunname between", value1, value2, "peixunname");
            return (Criteria) this;
        }

        public Criteria andPeixunnameNotBetween(String value1, String value2) {
            addCriterion("peixunname not between", value1, value2, "peixunname");
            return (Criteria) this;
        }

        public Criteria andPeixunidIsNull() {
            addCriterion("peixunid is null");
            return (Criteria) this;
        }

        public Criteria andPeixunidIsNotNull() {
            addCriterion("peixunid is not null");
            return (Criteria) this;
        }

        public Criteria andPeixunidEqualTo(Integer value) {
            addCriterion("peixunid =", value, "peixunid");
            return (Criteria) this;
        }

        public Criteria andPeixunidNotEqualTo(Integer value) {
            addCriterion("peixunid <>", value, "peixunid");
            return (Criteria) this;
        }

        public Criteria andPeixunidGreaterThan(Integer value) {
            addCriterion("peixunid >", value, "peixunid");
            return (Criteria) this;
        }

        public Criteria andPeixunidGreaterThanOrEqualTo(Integer value) {
            addCriterion("peixunid >=", value, "peixunid");
            return (Criteria) this;
        }

        public Criteria andPeixunidLessThan(Integer value) {
            addCriterion("peixunid <", value, "peixunid");
            return (Criteria) this;
        }

        public Criteria andPeixunidLessThanOrEqualTo(Integer value) {
            addCriterion("peixunid <=", value, "peixunid");
            return (Criteria) this;
        }

        public Criteria andPeixunidIn(List<Integer> values) {
            addCriterion("peixunid in", values, "peixunid");
            return (Criteria) this;
        }

        public Criteria andPeixunidNotIn(List<Integer> values) {
            addCriterion("peixunid not in", values, "peixunid");
            return (Criteria) this;
        }

        public Criteria andPeixunidBetween(Integer value1, Integer value2) {
            addCriterion("peixunid between", value1, value2, "peixunid");
            return (Criteria) this;
        }

        public Criteria andPeixunidNotBetween(Integer value1, Integer value2) {
            addCriterion("peixunid not between", value1, value2, "peixunid");
            return (Criteria) this;
        }

        public Criteria andDriverpeoplenameIsNull() {
            addCriterion("driverpeopleName is null");
            return (Criteria) this;
        }

        public Criteria andDriverpeoplenameIsNotNull() {
            addCriterion("driverpeopleName is not null");
            return (Criteria) this;
        }

        public Criteria andDriverpeoplenameEqualTo(String value) {
            addCriterion("driverpeopleName =", value, "driverpeoplename");
            return (Criteria) this;
        }

        public Criteria andDriverpeoplenameNotEqualTo(String value) {
            addCriterion("driverpeopleName <>", value, "driverpeoplename");
            return (Criteria) this;
        }

        public Criteria andDriverpeoplenameGreaterThan(String value) {
            addCriterion("driverpeopleName >", value, "driverpeoplename");
            return (Criteria) this;
        }

        public Criteria andDriverpeoplenameGreaterThanOrEqualTo(String value) {
            addCriterion("driverpeopleName >=", value, "driverpeoplename");
            return (Criteria) this;
        }

        public Criteria andDriverpeoplenameLessThan(String value) {
            addCriterion("driverpeopleName <", value, "driverpeoplename");
            return (Criteria) this;
        }

        public Criteria andDriverpeoplenameLessThanOrEqualTo(String value) {
            addCriterion("driverpeopleName <=", value, "driverpeoplename");
            return (Criteria) this;
        }

        public Criteria andDriverpeoplenameLike(String value) {
            addCriterion("driverpeopleName like", value, "driverpeoplename");
            return (Criteria) this;
        }

        public Criteria andDriverpeoplenameNotLike(String value) {
            addCriterion("driverpeopleName not like", value, "driverpeoplename");
            return (Criteria) this;
        }

        public Criteria andDriverpeoplenameIn(List<String> values) {
            addCriterion("driverpeopleName in", values, "driverpeoplename");
            return (Criteria) this;
        }

        public Criteria andDriverpeoplenameNotIn(List<String> values) {
            addCriterion("driverpeopleName not in", values, "driverpeoplename");
            return (Criteria) this;
        }

        public Criteria andDriverpeoplenameBetween(String value1, String value2) {
            addCriterion("driverpeopleName between", value1, value2, "driverpeoplename");
            return (Criteria) this;
        }

        public Criteria andDriverpeoplenameNotBetween(String value1, String value2) {
            addCriterion("driverpeopleName not between", value1, value2, "driverpeoplename");
            return (Criteria) this;
        }

        public Criteria andReserveOneIsNull() {
            addCriterion("reserve_one is null");
            return (Criteria) this;
        }

        public Criteria andReserveOneIsNotNull() {
            addCriterion("reserve_one is not null");
            return (Criteria) this;
        }

        public Criteria andReserveOneEqualTo(String value) {
            addCriterion("reserve_one =", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotEqualTo(String value) {
            addCriterion("reserve_one <>", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneGreaterThan(String value) {
            addCriterion("reserve_one >", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_one >=", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneLessThan(String value) {
            addCriterion("reserve_one <", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneLessThanOrEqualTo(String value) {
            addCriterion("reserve_one <=", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneLike(String value) {
            addCriterion("reserve_one like", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotLike(String value) {
            addCriterion("reserve_one not like", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneIn(List<String> values) {
            addCriterion("reserve_one in", values, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotIn(List<String> values) {
            addCriterion("reserve_one not in", values, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneBetween(String value1, String value2) {
            addCriterion("reserve_one between", value1, value2, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotBetween(String value1, String value2) {
            addCriterion("reserve_one not between", value1, value2, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIsNull() {
            addCriterion("reserve_two is null");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIsNotNull() {
            addCriterion("reserve_two is not null");
            return (Criteria) this;
        }

        public Criteria andReserveTwoEqualTo(String value) {
            addCriterion("reserve_two =", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotEqualTo(String value) {
            addCriterion("reserve_two <>", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoGreaterThan(String value) {
            addCriterion("reserve_two >", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_two >=", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLessThan(String value) {
            addCriterion("reserve_two <", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLessThanOrEqualTo(String value) {
            addCriterion("reserve_two <=", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLike(String value) {
            addCriterion("reserve_two like", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotLike(String value) {
            addCriterion("reserve_two not like", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIn(List<String> values) {
            addCriterion("reserve_two in", values, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotIn(List<String> values) {
            addCriterion("reserve_two not in", values, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoBetween(String value1, String value2) {
            addCriterion("reserve_two between", value1, value2, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotBetween(String value1, String value2) {
            addCriterion("reserve_two not between", value1, value2, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveThreeIsNull() {
            addCriterion("reserve_three is null");
            return (Criteria) this;
        }

        public Criteria andReserveThreeIsNotNull() {
            addCriterion("reserve_three is not null");
            return (Criteria) this;
        }

        public Criteria andReserveThreeEqualTo(String value) {
            addCriterion("reserve_three =", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotEqualTo(String value) {
            addCriterion("reserve_three <>", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeGreaterThan(String value) {
            addCriterion("reserve_three >", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_three >=", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeLessThan(String value) {
            addCriterion("reserve_three <", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeLessThanOrEqualTo(String value) {
            addCriterion("reserve_three <=", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeLike(String value) {
            addCriterion("reserve_three like", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotLike(String value) {
            addCriterion("reserve_three not like", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeIn(List<String> values) {
            addCriterion("reserve_three in", values, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotIn(List<String> values) {
            addCriterion("reserve_three not in", values, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeBetween(String value1, String value2) {
            addCriterion("reserve_three between", value1, value2, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotBetween(String value1, String value2) {
            addCriterion("reserve_three not between", value1, value2, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCompayIdIsNull() {
            addCriterion("compay_id is null");
            return (Criteria) this;
        }

        public Criteria andCompayIdIsNotNull() {
            addCriterion("compay_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompayIdEqualTo(Integer value) {
            addCriterion("compay_id =", value, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdNotEqualTo(Integer value) {
            addCriterion("compay_id <>", value, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdGreaterThan(Integer value) {
            addCriterion("compay_id >", value, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("compay_id >=", value, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdLessThan(Integer value) {
            addCriterion("compay_id <", value, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdLessThanOrEqualTo(Integer value) {
            addCriterion("compay_id <=", value, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdIn(List<Integer> values) {
            addCriterion("compay_id in", values, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdNotIn(List<Integer> values) {
            addCriterion("compay_id not in", values, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdBetween(Integer value1, Integer value2) {
            addCriterion("compay_id between", value1, value2, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdNotBetween(Integer value1, Integer value2) {
            addCriterion("compay_id not between", value1, value2, "compayId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hl_peixunstate
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 27 13:42:55 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hl_peixunstate
     *
     * @mbggenerated Wed Dec 27 13:42:55 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}