package cm.cn.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class HlPeopleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    public HlPeopleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andIdNumIsNull() {
            addCriterion("id_num is null");
            return (Criteria) this;
        }

        public Criteria andIdNumIsNotNull() {
            addCriterion("id_num is not null");
            return (Criteria) this;
        }

        public Criteria andIdNumEqualTo(String value) {
            addCriterion("id_num =", value, "idNum");
            return (Criteria) this;
        }

        public Criteria andIdNumNotEqualTo(String value) {
            addCriterion("id_num <>", value, "idNum");
            return (Criteria) this;
        }

        public Criteria andIdNumGreaterThan(String value) {
            addCriterion("id_num >", value, "idNum");
            return (Criteria) this;
        }

        public Criteria andIdNumGreaterThanOrEqualTo(String value) {
            addCriterion("id_num >=", value, "idNum");
            return (Criteria) this;
        }

        public Criteria andIdNumLessThan(String value) {
            addCriterion("id_num <", value, "idNum");
            return (Criteria) this;
        }

        public Criteria andIdNumLessThanOrEqualTo(String value) {
            addCriterion("id_num <=", value, "idNum");
            return (Criteria) this;
        }

        public Criteria andIdNumLike(String value) {
            addCriterion("id_num like", value, "idNum");
            return (Criteria) this;
        }

        public Criteria andIdNumNotLike(String value) {
            addCriterion("id_num not like", value, "idNum");
            return (Criteria) this;
        }

        public Criteria andIdNumIn(List<String> values) {
            addCriterion("id_num in", values, "idNum");
            return (Criteria) this;
        }

        public Criteria andIdNumNotIn(List<String> values) {
            addCriterion("id_num not in", values, "idNum");
            return (Criteria) this;
        }

        public Criteria andIdNumBetween(String value1, String value2) {
            addCriterion("id_num between", value1, value2, "idNum");
            return (Criteria) this;
        }

        public Criteria andIdNumNotBetween(String value1, String value2) {
            addCriterion("id_num not between", value1, value2, "idNum");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceIsNull() {
            addCriterion("drive_licence is null");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceIsNotNull() {
            addCriterion("drive_licence is not null");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceEqualTo(String value) {
            addCriterion("drive_licence =", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceNotEqualTo(String value) {
            addCriterion("drive_licence <>", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceGreaterThan(String value) {
            addCriterion("drive_licence >", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceGreaterThanOrEqualTo(String value) {
            addCriterion("drive_licence >=", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceLessThan(String value) {
            addCriterion("drive_licence <", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceLessThanOrEqualTo(String value) {
            addCriterion("drive_licence <=", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceLike(String value) {
            addCriterion("drive_licence like", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceNotLike(String value) {
            addCriterion("drive_licence not like", value, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceIn(List<String> values) {
            addCriterion("drive_licence in", values, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceNotIn(List<String> values) {
            addCriterion("drive_licence not in", values, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceBetween(String value1, String value2) {
            addCriterion("drive_licence between", value1, value2, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriveLicenceNotBetween(String value1, String value2) {
            addCriterion("drive_licence not between", value1, value2, "driveLicence");
            return (Criteria) this;
        }

        public Criteria andDriLicenceTimeIsNull() {
            addCriterion("dri_licence_time is null");
            return (Criteria) this;
        }

        public Criteria andDriLicenceTimeIsNotNull() {
            addCriterion("dri_licence_time is not null");
            return (Criteria) this;
        }

        public Criteria andDriLicenceTimeEqualTo(Date value) {
            addCriterionForJDBCDate("dri_licence_time =", value, "driLicenceTime");
            return (Criteria) this;
        }

        public Criteria andDriLicenceTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("dri_licence_time <>", value, "driLicenceTime");
            return (Criteria) this;
        }

        public Criteria andDriLicenceTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("dri_licence_time >", value, "driLicenceTime");
            return (Criteria) this;
        }

        public Criteria andDriLicenceTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("dri_licence_time >=", value, "driLicenceTime");
            return (Criteria) this;
        }

        public Criteria andDriLicenceTimeLessThan(Date value) {
            addCriterionForJDBCDate("dri_licence_time <", value, "driLicenceTime");
            return (Criteria) this;
        }

        public Criteria andDriLicenceTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("dri_licence_time <=", value, "driLicenceTime");
            return (Criteria) this;
        }

        public Criteria andDriLicenceTimeIn(List<Date> values) {
            addCriterionForJDBCDate("dri_licence_time in", values, "driLicenceTime");
            return (Criteria) this;
        }

        public Criteria andDriLicenceTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("dri_licence_time not in", values, "driLicenceTime");
            return (Criteria) this;
        }

        public Criteria andDriLicenceTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("dri_licence_time between", value1, value2, "driLicenceTime");
            return (Criteria) this;
        }

        public Criteria andDriLicenceTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("dri_licence_time not between", value1, value2, "driLicenceTime");
            return (Criteria) this;
        }

        public Criteria andCompayIdIsNull() {
            addCriterion("compay_id is null");
            return (Criteria) this;
        }

        public Criteria andCompayIdIsNotNull() {
            addCriterion("compay_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompayIdEqualTo(Integer value) {
            addCriterion("compay_id =", value, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdNotEqualTo(Integer value) {
            addCriterion("compay_id <>", value, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdGreaterThan(Integer value) {
            addCriterion("compay_id >", value, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("compay_id >=", value, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdLessThan(Integer value) {
            addCriterion("compay_id <", value, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdLessThanOrEqualTo(Integer value) {
            addCriterion("compay_id <=", value, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdIn(List<Integer> values) {
            addCriterion("compay_id in", values, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdNotIn(List<Integer> values) {
            addCriterion("compay_id not in", values, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdBetween(Integer value1, Integer value2) {
            addCriterion("compay_id between", value1, value2, "compayId");
            return (Criteria) this;
        }

        public Criteria andCompayIdNotBetween(Integer value1, Integer value2) {
            addCriterion("compay_id not between", value1, value2, "compayId");
            return (Criteria) this;
        }

        public Criteria andDrivezigezhengIsNull() {
            addCriterion("drivezigezheng is null");
            return (Criteria) this;
        }

        public Criteria andDrivezigezhengIsNotNull() {
            addCriterion("drivezigezheng is not null");
            return (Criteria) this;
        }

        public Criteria andDrivezigezhengEqualTo(String value) {
            addCriterion("drivezigezheng =", value, "drivezigezheng");
            return (Criteria) this;
        }

        public Criteria andDrivezigezhengNotEqualTo(String value) {
            addCriterion("drivezigezheng <>", value, "drivezigezheng");
            return (Criteria) this;
        }

        public Criteria andDrivezigezhengGreaterThan(String value) {
            addCriterion("drivezigezheng >", value, "drivezigezheng");
            return (Criteria) this;
        }

        public Criteria andDrivezigezhengGreaterThanOrEqualTo(String value) {
            addCriterion("drivezigezheng >=", value, "drivezigezheng");
            return (Criteria) this;
        }

        public Criteria andDrivezigezhengLessThan(String value) {
            addCriterion("drivezigezheng <", value, "drivezigezheng");
            return (Criteria) this;
        }

        public Criteria andDrivezigezhengLessThanOrEqualTo(String value) {
            addCriterion("drivezigezheng <=", value, "drivezigezheng");
            return (Criteria) this;
        }

        public Criteria andDrivezigezhengLike(String value) {
            addCriterion("drivezigezheng like", value, "drivezigezheng");
            return (Criteria) this;
        }

        public Criteria andDrivezigezhengNotLike(String value) {
            addCriterion("drivezigezheng not like", value, "drivezigezheng");
            return (Criteria) this;
        }

        public Criteria andDrivezigezhengIn(List<String> values) {
            addCriterion("drivezigezheng in", values, "drivezigezheng");
            return (Criteria) this;
        }

        public Criteria andDrivezigezhengNotIn(List<String> values) {
            addCriterion("drivezigezheng not in", values, "drivezigezheng");
            return (Criteria) this;
        }

        public Criteria andDrivezigezhengBetween(String value1, String value2) {
            addCriterion("drivezigezheng between", value1, value2, "drivezigezheng");
            return (Criteria) this;
        }

        public Criteria andDrivezigezhengNotBetween(String value1, String value2) {
            addCriterion("drivezigezheng not between", value1, value2, "drivezigezheng");
            return (Criteria) this;
        }

        public Criteria andDriverzigezhengTimeIsNull() {
            addCriterion("driverzigezheng_time is null");
            return (Criteria) this;
        }

        public Criteria andDriverzigezhengTimeIsNotNull() {
            addCriterion("driverzigezheng_time is not null");
            return (Criteria) this;
        }

        public Criteria andDriverzigezhengTimeEqualTo(Date value) {
            addCriterionForJDBCDate("driverzigezheng_time =", value, "driverzigezhengTime");
            return (Criteria) this;
        }

        public Criteria andDriverzigezhengTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("driverzigezheng_time <>", value, "driverzigezhengTime");
            return (Criteria) this;
        }

        public Criteria andDriverzigezhengTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("driverzigezheng_time >", value, "driverzigezhengTime");
            return (Criteria) this;
        }

        public Criteria andDriverzigezhengTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("driverzigezheng_time >=", value, "driverzigezhengTime");
            return (Criteria) this;
        }

        public Criteria andDriverzigezhengTimeLessThan(Date value) {
            addCriterionForJDBCDate("driverzigezheng_time <", value, "driverzigezhengTime");
            return (Criteria) this;
        }

        public Criteria andDriverzigezhengTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("driverzigezheng_time <=", value, "driverzigezhengTime");
            return (Criteria) this;
        }

        public Criteria andDriverzigezhengTimeIn(List<Date> values) {
            addCriterionForJDBCDate("driverzigezheng_time in", values, "driverzigezhengTime");
            return (Criteria) this;
        }

        public Criteria andDriverzigezhengTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("driverzigezheng_time not in", values, "driverzigezhengTime");
            return (Criteria) this;
        }

        public Criteria andDriverzigezhengTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("driverzigezheng_time between", value1, value2, "driverzigezhengTime");
            return (Criteria) this;
        }

        public Criteria andDriverzigezhengTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("driverzigezheng_time not between", value1, value2, "driverzigezhengTime");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceIsNull() {
            addCriterion("safe_licence is null");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceIsNotNull() {
            addCriterion("safe_licence is not null");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceEqualTo(String value) {
            addCriterion("safe_licence =", value, "safeLicence");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceNotEqualTo(String value) {
            addCriterion("safe_licence <>", value, "safeLicence");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceGreaterThan(String value) {
            addCriterion("safe_licence >", value, "safeLicence");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceGreaterThanOrEqualTo(String value) {
            addCriterion("safe_licence >=", value, "safeLicence");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceLessThan(String value) {
            addCriterion("safe_licence <", value, "safeLicence");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceLessThanOrEqualTo(String value) {
            addCriterion("safe_licence <=", value, "safeLicence");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceLike(String value) {
            addCriterion("safe_licence like", value, "safeLicence");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceNotLike(String value) {
            addCriterion("safe_licence not like", value, "safeLicence");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceIn(List<String> values) {
            addCriterion("safe_licence in", values, "safeLicence");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceNotIn(List<String> values) {
            addCriterion("safe_licence not in", values, "safeLicence");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceBetween(String value1, String value2) {
            addCriterion("safe_licence between", value1, value2, "safeLicence");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceNotBetween(String value1, String value2) {
            addCriterion("safe_licence not between", value1, value2, "safeLicence");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceTimeIsNull() {
            addCriterion("safe_licence_time is null");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceTimeIsNotNull() {
            addCriterion("safe_licence_time is not null");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceTimeEqualTo(Date value) {
            addCriterionForJDBCDate("safe_licence_time =", value, "safeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("safe_licence_time <>", value, "safeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("safe_licence_time >", value, "safeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("safe_licence_time >=", value, "safeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceTimeLessThan(Date value) {
            addCriterionForJDBCDate("safe_licence_time <", value, "safeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("safe_licence_time <=", value, "safeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceTimeIn(List<Date> values) {
            addCriterionForJDBCDate("safe_licence_time in", values, "safeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("safe_licence_time not in", values, "safeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("safe_licence_time between", value1, value2, "safeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andSafeLicenceTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("safe_licence_time not between", value1, value2, "safeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceIsNull() {
            addCriterion("charge_licence is null");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceIsNotNull() {
            addCriterion("charge_licence is not null");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceEqualTo(String value) {
            addCriterion("charge_licence =", value, "chargeLicence");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceNotEqualTo(String value) {
            addCriterion("charge_licence <>", value, "chargeLicence");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceGreaterThan(String value) {
            addCriterion("charge_licence >", value, "chargeLicence");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceGreaterThanOrEqualTo(String value) {
            addCriterion("charge_licence >=", value, "chargeLicence");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceLessThan(String value) {
            addCriterion("charge_licence <", value, "chargeLicence");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceLessThanOrEqualTo(String value) {
            addCriterion("charge_licence <=", value, "chargeLicence");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceLike(String value) {
            addCriterion("charge_licence like", value, "chargeLicence");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceNotLike(String value) {
            addCriterion("charge_licence not like", value, "chargeLicence");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceIn(List<String> values) {
            addCriterion("charge_licence in", values, "chargeLicence");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceNotIn(List<String> values) {
            addCriterion("charge_licence not in", values, "chargeLicence");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceBetween(String value1, String value2) {
            addCriterion("charge_licence between", value1, value2, "chargeLicence");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceNotBetween(String value1, String value2) {
            addCriterion("charge_licence not between", value1, value2, "chargeLicence");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceTimeIsNull() {
            addCriterion("charge_licence_time is null");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceTimeIsNotNull() {
            addCriterion("charge_licence_time is not null");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceTimeEqualTo(Date value) {
            addCriterionForJDBCDate("charge_licence_time =", value, "chargeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("charge_licence_time <>", value, "chargeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("charge_licence_time >", value, "chargeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("charge_licence_time >=", value, "chargeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceTimeLessThan(Date value) {
            addCriterionForJDBCDate("charge_licence_time <", value, "chargeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("charge_licence_time <=", value, "chargeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceTimeIn(List<Date> values) {
            addCriterionForJDBCDate("charge_licence_time in", values, "chargeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("charge_licence_time not in", values, "chargeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("charge_licence_time between", value1, value2, "chargeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andChargeLicenceTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("charge_licence_time not between", value1, value2, "chargeLicenceTime");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceIsNull() {
            addCriterion("upload_licence is null");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceIsNotNull() {
            addCriterion("upload_licence is not null");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceEqualTo(String value) {
            addCriterion("upload_licence =", value, "uploadLicence");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceNotEqualTo(String value) {
            addCriterion("upload_licence <>", value, "uploadLicence");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceGreaterThan(String value) {
            addCriterion("upload_licence >", value, "uploadLicence");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceGreaterThanOrEqualTo(String value) {
            addCriterion("upload_licence >=", value, "uploadLicence");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceLessThan(String value) {
            addCriterion("upload_licence <", value, "uploadLicence");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceLessThanOrEqualTo(String value) {
            addCriterion("upload_licence <=", value, "uploadLicence");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceLike(String value) {
            addCriterion("upload_licence like", value, "uploadLicence");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceNotLike(String value) {
            addCriterion("upload_licence not like", value, "uploadLicence");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceIn(List<String> values) {
            addCriterion("upload_licence in", values, "uploadLicence");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceNotIn(List<String> values) {
            addCriterion("upload_licence not in", values, "uploadLicence");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceBetween(String value1, String value2) {
            addCriterion("upload_licence between", value1, value2, "uploadLicence");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceNotBetween(String value1, String value2) {
            addCriterion("upload_licence not between", value1, value2, "uploadLicence");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceTimeIsNull() {
            addCriterion("upload_licence_time is null");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceTimeIsNotNull() {
            addCriterion("upload_licence_time is not null");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceTimeEqualTo(Date value) {
            addCriterionForJDBCDate("upload_licence_time =", value, "uploadLicenceTime");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("upload_licence_time <>", value, "uploadLicenceTime");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("upload_licence_time >", value, "uploadLicenceTime");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("upload_licence_time >=", value, "uploadLicenceTime");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceTimeLessThan(Date value) {
            addCriterionForJDBCDate("upload_licence_time <", value, "uploadLicenceTime");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("upload_licence_time <=", value, "uploadLicenceTime");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceTimeIn(List<Date> values) {
            addCriterionForJDBCDate("upload_licence_time in", values, "uploadLicenceTime");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("upload_licence_time not in", values, "uploadLicenceTime");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("upload_licence_time between", value1, value2, "uploadLicenceTime");
            return (Criteria) this;
        }

        public Criteria andUploadLicenceTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("upload_licence_time not between", value1, value2, "uploadLicenceTime");
            return (Criteria) this;
        }

        public Criteria andDriverTypeIsNull() {
            addCriterion("driver_type is null");
            return (Criteria) this;
        }

        public Criteria andDriverTypeIsNotNull() {
            addCriterion("driver_type is not null");
            return (Criteria) this;
        }

        public Criteria andDriverTypeEqualTo(String value) {
            addCriterion("driver_type =", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeNotEqualTo(String value) {
            addCriterion("driver_type <>", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeGreaterThan(String value) {
            addCriterion("driver_type >", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeGreaterThanOrEqualTo(String value) {
            addCriterion("driver_type >=", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeLessThan(String value) {
            addCriterion("driver_type <", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeLessThanOrEqualTo(String value) {
            addCriterion("driver_type <=", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeLike(String value) {
            addCriterion("driver_type like", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeNotLike(String value) {
            addCriterion("driver_type not like", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeIn(List<String> values) {
            addCriterion("driver_type in", values, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeNotIn(List<String> values) {
            addCriterion("driver_type not in", values, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeBetween(String value1, String value2) {
            addCriterion("driver_type between", value1, value2, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeNotBetween(String value1, String value2) {
            addCriterion("driver_type not between", value1, value2, "driverType");
            return (Criteria) this;
        }

        public Criteria andAdresssIsNull() {
            addCriterion("adresss is null");
            return (Criteria) this;
        }

        public Criteria andAdresssIsNotNull() {
            addCriterion("adresss is not null");
            return (Criteria) this;
        }

        public Criteria andAdresssEqualTo(String value) {
            addCriterion("adresss =", value, "adresss");
            return (Criteria) this;
        }

        public Criteria andAdresssNotEqualTo(String value) {
            addCriterion("adresss <>", value, "adresss");
            return (Criteria) this;
        }

        public Criteria andAdresssGreaterThan(String value) {
            addCriterion("adresss >", value, "adresss");
            return (Criteria) this;
        }

        public Criteria andAdresssGreaterThanOrEqualTo(String value) {
            addCriterion("adresss >=", value, "adresss");
            return (Criteria) this;
        }

        public Criteria andAdresssLessThan(String value) {
            addCriterion("adresss <", value, "adresss");
            return (Criteria) this;
        }

        public Criteria andAdresssLessThanOrEqualTo(String value) {
            addCriterion("adresss <=", value, "adresss");
            return (Criteria) this;
        }

        public Criteria andAdresssLike(String value) {
            addCriterion("adresss like", value, "adresss");
            return (Criteria) this;
        }

        public Criteria andAdresssNotLike(String value) {
            addCriterion("adresss not like", value, "adresss");
            return (Criteria) this;
        }

        public Criteria andAdresssIn(List<String> values) {
            addCriterion("adresss in", values, "adresss");
            return (Criteria) this;
        }

        public Criteria andAdresssNotIn(List<String> values) {
            addCriterion("adresss not in", values, "adresss");
            return (Criteria) this;
        }

        public Criteria andAdresssBetween(String value1, String value2) {
            addCriterion("adresss between", value1, value2, "adresss");
            return (Criteria) this;
        }

        public Criteria andAdresssNotBetween(String value1, String value2) {
            addCriterion("adresss not between", value1, value2, "adresss");
            return (Criteria) this;
        }

        public Criteria andReserveOneIsNull() {
            addCriterion("reserve_one is null");
            return (Criteria) this;
        }

        public Criteria andReserveOneIsNotNull() {
            addCriterion("reserve_one is not null");
            return (Criteria) this;
        }

        public Criteria andReserveOneEqualTo(String value) {
            addCriterion("reserve_one =", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotEqualTo(String value) {
            addCriterion("reserve_one <>", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneGreaterThan(String value) {
            addCriterion("reserve_one >", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_one >=", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneLessThan(String value) {
            addCriterion("reserve_one <", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneLessThanOrEqualTo(String value) {
            addCriterion("reserve_one <=", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneLike(String value) {
            addCriterion("reserve_one like", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotLike(String value) {
            addCriterion("reserve_one not like", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneIn(List<String> values) {
            addCriterion("reserve_one in", values, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotIn(List<String> values) {
            addCriterion("reserve_one not in", values, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneBetween(String value1, String value2) {
            addCriterion("reserve_one between", value1, value2, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotBetween(String value1, String value2) {
            addCriterion("reserve_one not between", value1, value2, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIsNull() {
            addCriterion("reserve_two is null");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIsNotNull() {
            addCriterion("reserve_two is not null");
            return (Criteria) this;
        }

        public Criteria andReserveTwoEqualTo(String value) {
            addCriterion("reserve_two =", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotEqualTo(String value) {
            addCriterion("reserve_two <>", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoGreaterThan(String value) {
            addCriterion("reserve_two >", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_two >=", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLessThan(String value) {
            addCriterion("reserve_two <", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLessThanOrEqualTo(String value) {
            addCriterion("reserve_two <=", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLike(String value) {
            addCriterion("reserve_two like", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotLike(String value) {
            addCriterion("reserve_two not like", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIn(List<String> values) {
            addCriterion("reserve_two in", values, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotIn(List<String> values) {
            addCriterion("reserve_two not in", values, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoBetween(String value1, String value2) {
            addCriterion("reserve_two between", value1, value2, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotBetween(String value1, String value2) {
            addCriterion("reserve_two not between", value1, value2, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveThreeIsNull() {
            addCriterion("reserve_three is null");
            return (Criteria) this;
        }

        public Criteria andReserveThreeIsNotNull() {
            addCriterion("reserve_three is not null");
            return (Criteria) this;
        }

        public Criteria andReserveThreeEqualTo(String value) {
            addCriterion("reserve_three =", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotEqualTo(String value) {
            addCriterion("reserve_three <>", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeGreaterThan(String value) {
            addCriterion("reserve_three >", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_three >=", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeLessThan(String value) {
            addCriterion("reserve_three <", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeLessThanOrEqualTo(String value) {
            addCriterion("reserve_three <=", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeLike(String value) {
            addCriterion("reserve_three like", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotLike(String value) {
            addCriterion("reserve_three not like", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeIn(List<String> values) {
            addCriterion("reserve_three in", values, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotIn(List<String> values) {
            addCriterion("reserve_three not in", values, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeBetween(String value1, String value2) {
            addCriterion("reserve_three between", value1, value2, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotBetween(String value1, String value2) {
            addCriterion("reserve_three not between", value1, value2, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andPictureNameIsNull() {
            addCriterion("picture_name is null");
            return (Criteria) this;
        }

        public Criteria andPictureNameIsNotNull() {
            addCriterion("picture_name is not null");
            return (Criteria) this;
        }

        public Criteria andPictureNameEqualTo(String value) {
            addCriterion("picture_name =", value, "pictureName");
            return (Criteria) this;
        }

        public Criteria andPictureNameNotEqualTo(String value) {
            addCriterion("picture_name <>", value, "pictureName");
            return (Criteria) this;
        }

        public Criteria andPictureNameGreaterThan(String value) {
            addCriterion("picture_name >", value, "pictureName");
            return (Criteria) this;
        }

        public Criteria andPictureNameGreaterThanOrEqualTo(String value) {
            addCriterion("picture_name >=", value, "pictureName");
            return (Criteria) this;
        }

        public Criteria andPictureNameLessThan(String value) {
            addCriterion("picture_name <", value, "pictureName");
            return (Criteria) this;
        }

        public Criteria andPictureNameLessThanOrEqualTo(String value) {
            addCriterion("picture_name <=", value, "pictureName");
            return (Criteria) this;
        }

        public Criteria andPictureNameLike(String value) {
            addCriterion("picture_name like", value, "pictureName");
            return (Criteria) this;
        }

        public Criteria andPictureNameNotLike(String value) {
            addCriterion("picture_name not like", value, "pictureName");
            return (Criteria) this;
        }

        public Criteria andPictureNameIn(List<String> values) {
            addCriterion("picture_name in", values, "pictureName");
            return (Criteria) this;
        }

        public Criteria andPictureNameNotIn(List<String> values) {
            addCriterion("picture_name not in", values, "pictureName");
            return (Criteria) this;
        }

        public Criteria andPictureNameBetween(String value1, String value2) {
            addCriterion("picture_name between", value1, value2, "pictureName");
            return (Criteria) this;
        }

        public Criteria andPictureNameNotBetween(String value1, String value2) {
            addCriterion("picture_name not between", value1, value2, "pictureName");
            return (Criteria) this;
        }

        public Criteria andPictureUrlIsNull() {
            addCriterion("picture_url is null");
            return (Criteria) this;
        }

        public Criteria andPictureUrlIsNotNull() {
            addCriterion("picture_url is not null");
            return (Criteria) this;
        }

        public Criteria andPictureUrlEqualTo(String value) {
            addCriterion("picture_url =", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlNotEqualTo(String value) {
            addCriterion("picture_url <>", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlGreaterThan(String value) {
            addCriterion("picture_url >", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlGreaterThanOrEqualTo(String value) {
            addCriterion("picture_url >=", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlLessThan(String value) {
            addCriterion("picture_url <", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlLessThanOrEqualTo(String value) {
            addCriterion("picture_url <=", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlLike(String value) {
            addCriterion("picture_url like", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlNotLike(String value) {
            addCriterion("picture_url not like", value, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlIn(List<String> values) {
            addCriterion("picture_url in", values, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlNotIn(List<String> values) {
            addCriterion("picture_url not in", values, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlBetween(String value1, String value2) {
            addCriterion("picture_url between", value1, value2, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPictureUrlNotBetween(String value1, String value2) {
            addCriterion("picture_url not between", value1, value2, "pictureUrl");
            return (Criteria) this;
        }

        public Criteria andPeopleTypeIsNull() {
            addCriterion("people_type is null");
            return (Criteria) this;
        }

        public Criteria andPeopleTypeIsNotNull() {
            addCriterion("people_type is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleTypeEqualTo(String value) {
            addCriterion("people_type =", value, "peopleType");
            return (Criteria) this;
        }

        public Criteria andPeopleTypeNotEqualTo(String value) {
            addCriterion("people_type <>", value, "peopleType");
            return (Criteria) this;
        }

        public Criteria andPeopleTypeGreaterThan(String value) {
            addCriterion("people_type >", value, "peopleType");
            return (Criteria) this;
        }

        public Criteria andPeopleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("people_type >=", value, "peopleType");
            return (Criteria) this;
        }

        public Criteria andPeopleTypeLessThan(String value) {
            addCriterion("people_type <", value, "peopleType");
            return (Criteria) this;
        }

        public Criteria andPeopleTypeLessThanOrEqualTo(String value) {
            addCriterion("people_type <=", value, "peopleType");
            return (Criteria) this;
        }

        public Criteria andPeopleTypeLike(String value) {
            addCriterion("people_type like", value, "peopleType");
            return (Criteria) this;
        }

        public Criteria andPeopleTypeNotLike(String value) {
            addCriterion("people_type not like", value, "peopleType");
            return (Criteria) this;
        }

        public Criteria andPeopleTypeIn(List<String> values) {
            addCriterion("people_type in", values, "peopleType");
            return (Criteria) this;
        }

        public Criteria andPeopleTypeNotIn(List<String> values) {
            addCriterion("people_type not in", values, "peopleType");
            return (Criteria) this;
        }

        public Criteria andPeopleTypeBetween(String value1, String value2) {
            addCriterion("people_type between", value1, value2, "peopleType");
            return (Criteria) this;
        }

        public Criteria andPeopleTypeNotBetween(String value1, String value2) {
            addCriterion("people_type not between", value1, value2, "peopleType");
            return (Criteria) this;
        }

        public Criteria andPeopleStatusIsNull() {
            addCriterion("people_status is null");
            return (Criteria) this;
        }

        public Criteria andPeopleStatusIsNotNull() {
            addCriterion("people_status is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleStatusEqualTo(String value) {
            addCriterion("people_status =", value, "peopleStatus");
            return (Criteria) this;
        }

        public Criteria andPeopleStatusNotEqualTo(String value) {
            addCriterion("people_status <>", value, "peopleStatus");
            return (Criteria) this;
        }

        public Criteria andPeopleStatusGreaterThan(String value) {
            addCriterion("people_status >", value, "peopleStatus");
            return (Criteria) this;
        }

        public Criteria andPeopleStatusGreaterThanOrEqualTo(String value) {
            addCriterion("people_status >=", value, "peopleStatus");
            return (Criteria) this;
        }

        public Criteria andPeopleStatusLessThan(String value) {
            addCriterion("people_status <", value, "peopleStatus");
            return (Criteria) this;
        }

        public Criteria andPeopleStatusLessThanOrEqualTo(String value) {
            addCriterion("people_status <=", value, "peopleStatus");
            return (Criteria) this;
        }

        public Criteria andPeopleStatusLike(String value) {
            addCriterion("people_status like", value, "peopleStatus");
            return (Criteria) this;
        }

        public Criteria andPeopleStatusNotLike(String value) {
            addCriterion("people_status not like", value, "peopleStatus");
            return (Criteria) this;
        }

        public Criteria andPeopleStatusIn(List<String> values) {
            addCriterion("people_status in", values, "peopleStatus");
            return (Criteria) this;
        }

        public Criteria andPeopleStatusNotIn(List<String> values) {
            addCriterion("people_status not in", values, "peopleStatus");
            return (Criteria) this;
        }

        public Criteria andPeopleStatusBetween(String value1, String value2) {
            addCriterion("people_status between", value1, value2, "peopleStatus");
            return (Criteria) this;
        }

        public Criteria andPeopleStatusNotBetween(String value1, String value2) {
            addCriterion("people_status not between", value1, value2, "peopleStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hl_people
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 19 09:31:23 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hl_people
     *
     * @mbggenerated Tue Dec 19 09:31:23 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}