package cm.cn.po;

import java.util.Date;

public class HlWaybill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.id
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.shipper
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String shipper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.consign_date
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private Date consignDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.loading_date
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private Date loadingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.upload_date
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private Date uploadDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.send_place
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String sendPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.send_city
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String sendCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.load_place
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String loadPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.load_linkman
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String loadLinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.compay_id
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private Integer compayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.load_linkman_phone
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String loadLinkmanPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.receive_place
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String receivePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.receive_city
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String receiveCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.upload_adress
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String uploadAdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.upload_linkman
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String uploadLinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.upload_linkman_phone
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String uploadLinkmanPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.good_name
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String goodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.goods_id
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.nation_code
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String nationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.code
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.total
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.weight
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.volume
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private Double volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.freight
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private Double freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.car_num
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String carNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.reserve_one
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String reserveOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.reserve_two
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String reserveTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.reserve_three
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private String reserveThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hl_waybill.waybill_state
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    private Integer waybillState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.id
     *
     * @return the value of hl_waybill.id
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.id
     *
     * @param id the value for hl_waybill.id
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.shipper
     *
     * @return the value of hl_waybill.shipper
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getShipper() {
        return shipper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.shipper
     *
     * @param shipper the value for hl_waybill.shipper
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setShipper(String shipper) {
        this.shipper = shipper == null ? null : shipper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.consign_date
     *
     * @return the value of hl_waybill.consign_date
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public Date getConsignDate() {
        return consignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.consign_date
     *
     * @param consignDate the value for hl_waybill.consign_date
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setConsignDate(Date consignDate) {
        this.consignDate = consignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.loading_date
     *
     * @return the value of hl_waybill.loading_date
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public Date getLoadingDate() {
        return loadingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.loading_date
     *
     * @param loadingDate the value for hl_waybill.loading_date
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setLoadingDate(Date loadingDate) {
        this.loadingDate = loadingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.upload_date
     *
     * @return the value of hl_waybill.upload_date
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.upload_date
     *
     * @param uploadDate the value for hl_waybill.upload_date
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.send_place
     *
     * @return the value of hl_waybill.send_place
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getSendPlace() {
        return sendPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.send_place
     *
     * @param sendPlace the value for hl_waybill.send_place
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setSendPlace(String sendPlace) {
        this.sendPlace = sendPlace == null ? null : sendPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.send_city
     *
     * @return the value of hl_waybill.send_city
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getSendCity() {
        return sendCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.send_city
     *
     * @param sendCity the value for hl_waybill.send_city
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setSendCity(String sendCity) {
        this.sendCity = sendCity == null ? null : sendCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.load_place
     *
     * @return the value of hl_waybill.load_place
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getLoadPlace() {
        return loadPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.load_place
     *
     * @param loadPlace the value for hl_waybill.load_place
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setLoadPlace(String loadPlace) {
        this.loadPlace = loadPlace == null ? null : loadPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.load_linkman
     *
     * @return the value of hl_waybill.load_linkman
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getLoadLinkman() {
        return loadLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.load_linkman
     *
     * @param loadLinkman the value for hl_waybill.load_linkman
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setLoadLinkman(String loadLinkman) {
        this.loadLinkman = loadLinkman == null ? null : loadLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.compay_id
     *
     * @return the value of hl_waybill.compay_id
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public Integer getCompayId() {
        return compayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.compay_id
     *
     * @param compayId the value for hl_waybill.compay_id
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setCompayId(Integer compayId) {
        this.compayId = compayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.load_linkman_phone
     *
     * @return the value of hl_waybill.load_linkman_phone
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getLoadLinkmanPhone() {
        return loadLinkmanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.load_linkman_phone
     *
     * @param loadLinkmanPhone the value for hl_waybill.load_linkman_phone
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setLoadLinkmanPhone(String loadLinkmanPhone) {
        this.loadLinkmanPhone = loadLinkmanPhone == null ? null : loadLinkmanPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.receive_place
     *
     * @return the value of hl_waybill.receive_place
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getReceivePlace() {
        return receivePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.receive_place
     *
     * @param receivePlace the value for hl_waybill.receive_place
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setReceivePlace(String receivePlace) {
        this.receivePlace = receivePlace == null ? null : receivePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.receive_city
     *
     * @return the value of hl_waybill.receive_city
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getReceiveCity() {
        return receiveCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.receive_city
     *
     * @param receiveCity the value for hl_waybill.receive_city
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setReceiveCity(String receiveCity) {
        this.receiveCity = receiveCity == null ? null : receiveCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.upload_adress
     *
     * @return the value of hl_waybill.upload_adress
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getUploadAdress() {
        return uploadAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.upload_adress
     *
     * @param uploadAdress the value for hl_waybill.upload_adress
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setUploadAdress(String uploadAdress) {
        this.uploadAdress = uploadAdress == null ? null : uploadAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.upload_linkman
     *
     * @return the value of hl_waybill.upload_linkman
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getUploadLinkman() {
        return uploadLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.upload_linkman
     *
     * @param uploadLinkman the value for hl_waybill.upload_linkman
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setUploadLinkman(String uploadLinkman) {
        this.uploadLinkman = uploadLinkman == null ? null : uploadLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.upload_linkman_phone
     *
     * @return the value of hl_waybill.upload_linkman_phone
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getUploadLinkmanPhone() {
        return uploadLinkmanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.upload_linkman_phone
     *
     * @param uploadLinkmanPhone the value for hl_waybill.upload_linkman_phone
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setUploadLinkmanPhone(String uploadLinkmanPhone) {
        this.uploadLinkmanPhone = uploadLinkmanPhone == null ? null : uploadLinkmanPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.good_name
     *
     * @return the value of hl_waybill.good_name
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getGoodName() {
        return goodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.good_name
     *
     * @param goodName the value for hl_waybill.good_name
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setGoodName(String goodName) {
        this.goodName = goodName == null ? null : goodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.goods_id
     *
     * @return the value of hl_waybill.goods_id
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.goods_id
     *
     * @param goodsId the value for hl_waybill.goods_id
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.nation_code
     *
     * @return the value of hl_waybill.nation_code
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getNationCode() {
        return nationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.nation_code
     *
     * @param nationCode the value for hl_waybill.nation_code
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setNationCode(String nationCode) {
        this.nationCode = nationCode == null ? null : nationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.code
     *
     * @return the value of hl_waybill.code
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.code
     *
     * @param code the value for hl_waybill.code
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.total
     *
     * @return the value of hl_waybill.total
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.total
     *
     * @param total the value for hl_waybill.total
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.weight
     *
     * @return the value of hl_waybill.weight
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.weight
     *
     * @param weight the value for hl_waybill.weight
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.volume
     *
     * @return the value of hl_waybill.volume
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public Double getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.volume
     *
     * @param volume the value for hl_waybill.volume
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setVolume(Double volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.freight
     *
     * @return the value of hl_waybill.freight
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public Double getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.freight
     *
     * @param freight the value for hl_waybill.freight
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setFreight(Double freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.car_num
     *
     * @return the value of hl_waybill.car_num
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getCarNum() {
        return carNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.car_num
     *
     * @param carNum the value for hl_waybill.car_num
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setCarNum(String carNum) {
        this.carNum = carNum == null ? null : carNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.reserve_one
     *
     * @return the value of hl_waybill.reserve_one
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.reserve_one
     *
     * @param reserveOne the value for hl_waybill.reserve_one
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setReserveOne(String reserveOne) {
        this.reserveOne = reserveOne == null ? null : reserveOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.reserve_two
     *
     * @return the value of hl_waybill.reserve_two
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.reserve_two
     *
     * @param reserveTwo the value for hl_waybill.reserve_two
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo == null ? null : reserveTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.reserve_three
     *
     * @return the value of hl_waybill.reserve_three
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public String getReserveThree() {
        return reserveThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.reserve_three
     *
     * @param reserveThree the value for hl_waybill.reserve_three
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setReserveThree(String reserveThree) {
        this.reserveThree = reserveThree == null ? null : reserveThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hl_waybill.waybill_state
     *
     * @return the value of hl_waybill.waybill_state
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public Integer getWaybillState() {
        return waybillState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hl_waybill.waybill_state
     *
     * @param waybillState the value for hl_waybill.waybill_state
     *
     * @mbggenerated Tue Oct 31 15:26:30 CST 2017
     */
    public void setWaybillState(Integer waybillState) {
        this.waybillState = waybillState;
    }
}