package cm.cn.mapper;

import cm.cn.po.HlCarinfo;
import cm.cn.po.HlCarinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HlCarinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    int countByExample(HlCarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    int deleteByExample(HlCarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    int insert(HlCarinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    int insertSelective(HlCarinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    List<HlCarinfo> selectByExample(HlCarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    HlCarinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    int updateByExampleSelective(@Param("record") HlCarinfo record, @Param("example") HlCarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    int updateByExample(@Param("record") HlCarinfo record, @Param("example") HlCarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    int updateByPrimaryKeySelective(HlCarinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_carinfo
     *
     * @mbggenerated Thu Sep 21 11:01:08 CST 2017
     */
    int updateByPrimaryKey(HlCarinfo record);
}