package cm.cn.mapper;

import cm.cn.po.HlCompany;
import cm.cn.po.HlCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HlCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_company
     *
     * @mbggenerated Fri Sep 15 17:56:06 CST 2017
     */
    int countByExample(HlCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_company
     *
     * @mbggenerated Fri Sep 15 17:56:06 CST 2017
     */
    int deleteByExample(HlCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_company
     *
     * @mbggenerated Fri Sep 15 17:56:06 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_company
     *
     * @mbggenerated Fri Sep 15 17:56:06 CST 2017
     */
    int insert(HlCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_company
     *
     * @mbggenerated Fri Sep 15 17:56:06 CST 2017
     */
    int insertSelective(HlCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_company
     *
     * @mbggenerated Fri Sep 15 17:56:06 CST 2017
     */
    List<HlCompany> selectByExample(HlCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_company
     *
     * @mbggenerated Fri Sep 15 17:56:06 CST 2017
     */
    HlCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_company
     *
     * @mbggenerated Fri Sep 15 17:56:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") HlCompany record, @Param("example") HlCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_company
     *
     * @mbggenerated Fri Sep 15 17:56:06 CST 2017
     */
    int updateByExample(@Param("record") HlCompany record, @Param("example") HlCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_company
     *
     * @mbggenerated Fri Sep 15 17:56:06 CST 2017
     */
    int updateByPrimaryKeySelective(HlCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_company
     *
     * @mbggenerated Fri Sep 15 17:56:06 CST 2017
     */
    int updateByPrimaryKey(HlCompany record);
}