package cm.cn.mapper;

import cm.cn.po.HlDriverlogText;
import cm.cn.po.HlDriverlogTextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HlDriverlogTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_driverlog_text
     *
     * @mbggenerated Thu Sep 21 17:04:30 CST 2017
     */
    int countByExample(HlDriverlogTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_driverlog_text
     *
     * @mbggenerated Thu Sep 21 17:04:30 CST 2017
     */
    int deleteByExample(HlDriverlogTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_driverlog_text
     *
     * @mbggenerated Thu Sep 21 17:04:30 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_driverlog_text
     *
     * @mbggenerated Thu Sep 21 17:04:30 CST 2017
     */
    int insert(HlDriverlogText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_driverlog_text
     *
     * @mbggenerated Thu Sep 21 17:04:30 CST 2017
     */
    int insertSelective(HlDriverlogText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_driverlog_text
     *
     * @mbggenerated Thu Sep 21 17:04:30 CST 2017
     */
    List<HlDriverlogText> selectByExample(HlDriverlogTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_driverlog_text
     *
     * @mbggenerated Thu Sep 21 17:04:30 CST 2017
     */
    HlDriverlogText selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_driverlog_text
     *
     * @mbggenerated Thu Sep 21 17:04:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") HlDriverlogText record, @Param("example") HlDriverlogTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_driverlog_text
     *
     * @mbggenerated Thu Sep 21 17:04:30 CST 2017
     */
    int updateByExample(@Param("record") HlDriverlogText record, @Param("example") HlDriverlogTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_driverlog_text
     *
     * @mbggenerated Thu Sep 21 17:04:30 CST 2017
     */
    int updateByPrimaryKeySelective(HlDriverlogText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hl_driverlog_text
     *
     * @mbggenerated Thu Sep 21 17:04:30 CST 2017
     */
    int updateByPrimaryKey(HlDriverlogText record);
}